import { createContext, useContext, useState, ReactNode } from "react";

const translations = {
  en: {
    title: "Tribal Affairs Portal",
    subtitle: "Government of India",
    citizen: "I am a Citizen",
    officer: "I am an Officer",
    newApplication: "New Application",
    applicationStatus: "Application Status",
    startApplication: "Start Application",
    checkStatus: "Check Status",
    backButton: "← Go Back",
    citizenServices: "Citizen Services",
    availableSchemes: "Available Schemes",
    applyNow: "Apply Now",
    personalInfo: "Personal Information",
    additionalInfo: "Additional Information",
    documents: "Documents",
    schemeSelection: "Scheme Selection",
    fullName: "Full Name",
    aadhaar: "Aadhaar Number",
    mobile: "Mobile Number",
    email: "Email Address",
    dob: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    fatherName: "Father's Name",
    caste: "Caste/Tribe",
    address: "Complete Address",
    village: "Village",
    district: "District",
    state: "State",
    pincode: "Pin Code",
    uploadDocuments: "Upload Required Documents",
    selectSchemes: "Select Schemes",
    submit: "Submit",
    next: "Next",
    previous: "Previous",
    back: "Back",
    applicationSubmitted: "Application Submitted Successfully",
    yourApplicationId: "Your Application ID",
    keepThisId: "Please keep this ID safe for future reference",
    returnToDashboard: "Return to Dashboard",
    downloadReceipt: "Download Receipt",
    // Officer Dashboard
    officerDashboard: "Officer Dashboard",
    welcomeBack: "Welcome back, manage tribal applications and land records",
    generateReport: "Generate Report",
    openMapView: "Open Map View",
    pendingApplications: "Pending Applications",
    approvedThisMonth: "Approved This Month",
    rejectedApplications: "Rejected Applications",
    landMarked: "Land Marked",
    applications: "Applications",
    analytics: "Analytics",
    landRecords: "Land Records",
    aiSupport: "AI Support",
    documentUpload: "Document Upload",
    uploadFRADocuments: "Upload FRA Documents",
    ocrExtraction: "OCR Text Extraction",
    aiDecisionSupport: "AI Decision Support System",
    exportReports: "Export Reports",
    extractText: "Extract Text",
    editText: "Edit Text",
    saveChanges: "Save Changes",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    processingDocument: "Processing document...",
    textExtracted: "Text extracted successfully",
    reviewAndEdit: "Review and edit extracted text"
  },
  hi: {
    title: "जनजातीय मामले पोर्टल",
    subtitle: "भारत सरकार",
    citizen: "मैं नागरिक हूं",
    officer: "मैं अधिकारी हूं",
    newApplication: "नया आवेदन",
    applicationStatus: "आवेदन की स्थिति",
    startApplication: "आवेदन शुरू करें",
    checkStatus: "स्थिति देखें",
    backButton: "← वापस जाएं",
    citizenServices: "नागरिक सेवाएं",
    availableSchemes: "उपलब्ध योजनाएं",
    applyNow: "आवेदन करें",
    personalInfo: "व्यक्तिगत जानकारी",
    additionalInfo: "पूरी जानकारी",
    documents: "दस्तावेज अपलोड",
    schemeSelection: "योजना चयन",
    fullName: "पूरा नाम",
    aadhaar: "आधार नंबर",
    mobile: "मोबाइल नंबर",
    email: "ईमेल पता",
    dob: "जन्म तारीख",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    fatherName: "पिता का नाम",
    caste: "जाति",
    address: "पूरा पता",
    village: "गांव",
    district: "जिला",
    state: "राज्य",
    pincode: "पिन कोड",
    uploadDocuments: "आवश्यक दस्तावेज अपलोड करें",
    selectSchemes: "योजनाओं का चयन करें",
    submit: "सबमिट करें",
    next: "अगला",
    previous: "पिछला",
    back: "वापस",
    applicationSubmitted: "आवेदन सफलतापूर्वक जमा हो गया",
    yourApplicationId: "आपका आवेदन नंबर",
    keepThisId: "कृपया इस नंबर को भविष्य के लिए संभाल कर रखें",
    returnToDashboard: "डैशबोर्ड पर वापस जाएं",
    downloadReceipt: "रसीद डाउनलोड करें",
    // Officer Dashboard
    officerDashboard: "अधिकारी डैशबोर्ड",
    welcomeBack: "वापस स्वागत है, जनजातीय आवेदन और भूमि रिकॉर्ड प्रबंधित करें",
    generateReport: "रिपोर्ट तैयार करें",
    openMapView: "मानचित्र दृश्य खोलें",
    pendingApplications: "लंबित आवेदन",
    approvedThisMonth: "इस महीने स्वीकृत",
    rejectedApplications: "अस्वीकृत आवेदन",
    landMarked: "भूमि चिह्नित",
    applications: "आवेदन",
    analytics: "विश्लेषण",
    landRecords: "भूमि रिकॉर्ड",
    aiSupport: "AI सहायता",
    documentUpload: "दस्तावेज़ अपलोड",
    uploadFRADocuments: "FRA दस्तावेज़ अपलोड करें",
    ocrExtraction: "OCR पाठ निष्कर्षण",
    aiDecisionSupport: "AI निर्णय सहायता प्रणाली",
    exportReports: "रिपोर्ट निर्यात",
    extractText: "पाठ निकालें",
    editText: "पाठ संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    exportPDF: "PDF निर्यात",
    exportExcel: "एक्सेल निर्यात",
    processingDocument: "दस्तावेज़ प्रसंस्करण...",
    textExtracted: "पाठ सफलतापूर्वक निकाला गया",
    reviewAndEdit: "निकाले गए पाठ की समीक्षा और संपादन करें"
  },
  mr: {
    title: "आदिवासी व्यवहार पोर्टल",
    subtitle: "भारत सरकार",
    citizen: "मी नागरिक आहे",
    officer: "मी अधिकारी आहे",
    newApplication: "नवीन अर्ज",
    applicationStatus: "अर्जाची स्थिती",
    startApplication: "अर्ज सुरू करा",
    checkStatus: "स्थिती तपासा",
    backButton: "← परत जा",
    citizenServices: "नागरिक सेवा",
    availableSchemes: "उपलब्ध योजना",
    applyNow: "आता अर्ज करा",
    personalInfo: "वैयक्तिक माहिती",
    additionalInfo: "अतिरिक्त माहिती",
    documents: "कागदपत्रे",
    schemeSelection: "योजना निवड",
    fullName: "पूर्ण नाव",
    aadhaar: "आधार क्रमांक",
    mobile: "मोबाइल नंबर",
    email: "ईमेल पत्ता",
    dob: "जन्म तारीख",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "इतर",
    fatherName: "वडिलांचे नाव",
    caste: "जात",
    address: "पूर्ण पत्ता",
    village: "गाव",
    district: "जिल्हा",
    state: "राज्य",
    pincode: "पिन कोड",
    uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
    selectSchemes: "योजना निवडा",
    submit: "सबमिट करा",
    next: "पुढे",
    previous: "मागे",
    back: "परत",
    applicationSubmitted: "अर्ज यशस्वीरित्या सबमिट झाला",
    yourApplicationId: "तुमचा अर्ज क्रमांक",
    keepThisId: "कृपया हा क्रमांक भविष्यासाठी सुरक्षित ठेवा",
    returnToDashboard: "डॅशबोर्डवर परत जा",
    downloadReceipt: "रसीद डाउनलोड करा",
    officerDashboard: "अधिकारी डॅशबोर्ड",
    welcomeBack: "परत स्वागत, आदिवासी अर्ज आणि जमीन रेकॉर्ड व्यवस्थापित करा",
    generateReport: "अहवाल तयार करा",
    openMapView: "नकाशा दृश्य उघडा",
    pendingApplications: "प्रलंबित अर्ज",
    approvedThisMonth: "या महिन्यात मंजूर",
    rejectedApplications: "नाकारलेले अर्ज",
    landMarked: "जमीन चिन्हांकित",
    applications: "अर्ज",
    analytics: "विश्लेषण",
    landRecords: "जमीन रेकॉर्ड",
    aiSupport: "AI सहाय्य",
    documentUpload: "दस्तऐवज अपलोड",
    uploadFRADocuments: "FRA दस्तऐवज अपलोड करा",
    ocrExtraction: "OCR मजकूर काढणे",
    aiDecisionSupport: "AI निर्णय सहाय्य प्रणाली",
    exportReports: "अहवाल निर्यात",
    extractText: "मजकूर काढा",
    editText: "मजकूर संपादित करा",
    saveChanges: "बदल सेव्ह करा",
    exportPDF: "PDF निर्यात",
    exportExcel: "एक्सेल निर्यात",
    processingDocument: "दस्तऐवज प्रक्रिया...",
    textExtracted: "मजकूर यशस्वीरित्या काढला",
    reviewAndEdit: "काढलेल्या मजकुराचे पुनरावलोकन आणि संपादन करा"
  },
  gu: {
    title: "આદિવાસી બાબતોનું પોર્ટલ",
    subtitle: "ભારત સરકાર",
    citizen: "હું નાગરિક છું",
    officer: "હું અધિકારી છું",
    newApplication: "નવી અરજી",
    applicationStatus: "અરજીની સ્થિતિ",
    startApplication: "અરજી શરૂ કરો",
    checkStatus: "સ્થિતિ તપાસો",
    backButton: "← પાછા જાઓ",
    citizenServices: "નાગરિક સેવાઓ",
    availableSchemes: "ઉપલબ્ધ યોજનાઓ",
    applyNow: "હવે અરજી કરો",
    personalInfo: "વ્યક્તિગત માહિતી",
    additionalInfo: "વધારાની માહિતી",
    documents: "દસ્તાવેજો",
    schemeSelection: "યોજના પસંદગી",
    fullName: "પૂરું નામ",
    aadhaar: "આધાર નંબર",
    mobile: "મોબાઇલ નંબર",
    email: "ઇમેઇલ સરનામું",
    dob: "જન્મ તારીખ",
    gender: "લિંગ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    fatherName: "પિતાનું નામ",
    caste: "જાતિ",
    address: "સંપૂર્ણ સરનામું",
    village: "ગામ",
    district: "જિલ્લો",
    state: "રાજ્ય",
    pincode: "પિન કોડ",
    uploadDocuments: "જરૂરી દસ્તાવેજો અપલોડ કરો",
    selectSchemes: "યોજનાઓ પસંદ કરો",
    submit: "સબમિટ કરો",
    next: "આગળ",
    previous: "પાછળ",
    back: "પાછા",
    applicationSubmitted: "અરજી સફળતાપૂર્વક સબમિટ થઈ",
    yourApplicationId: "તમારો અરજી નંબર",
    keepThisId: "કૃપા કરીને આ નંબર ભવિષ્ય માટે સુરક્ષિત રાખો",
    returnToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
    downloadReceipt: "રસીદ ડાઉનલોડ કરો",
    officerDashboard: "અધિકારી ડેશબોર્ડ",
    welcomeBack: "પાછા સ્વાગત, આદિવાસી અરજીઓ અને જમીન રેકોર્ડનું સંચાલન કરો",
    generateReport: "રિપોર્ટ જનરેટ કરો",
    openMapView: "મેપ વ્યૂ ખોલો",
    pendingApplications: "પેન્ડિંગ અરજીઓ",
    approvedThisMonth: "આ મહિને મંજૂર",
    rejectedApplications: "નકારેલી અરજીઓ",
    landMarked: "જમીન ચિહ્નિત",
    applications: "અરજીઓ",
    analytics: "વિશ્લેષણ",
    landRecords: "જમીન રેકોર્ડ",
    aiSupport: "AI સહાય",
    documentUpload: "દસ્તાવેજ અપલોડ",
    uploadFRADocuments: "FRA દસ્તાવેજો અપલોડ કરો",
    ocrExtraction: "OCR ટેક્સ્ટ એક્સટ્રેક્શન",
    aiDecisionSupport: "AI ડિસિઝન સપોર્ટ સિસ્ટમ",
    exportReports: "રિપોર્ટ્સ એક્સપોર્ટ",
    extractText: "ટેક્સ્ટ એક્સટ્રેક્ટ કરો",
    editText: "ટેક્સ્ટ એડિટ કરો",
    saveChanges: "ચેન્જ સેવ કરો",
    exportPDF: "PDF એક્સપોર્ટ",
    exportExcel: "એક્સેલ એક્સપોર્ટ",
    processingDocument: "દસ્તાવેજ પ્રોસેસિંગ...",
    textExtracted: "ટેક્સ્ટ સફળતાપૂર્વક એક્સટ્રેક્ટ થયું",
    reviewAndEdit: "એક્સટ્રેક્ટ થયેલા ટેક્સ્ટની સમીક્ષા અને સંપાદન કરો"
  },
  bn: {
    title: "উপজাতীয় বিষয়ক পোর্টাল",
    subtitle: "ভারত সরকার",
    citizen: "আমি একজন নাগরিক",
    officer: "আমি একজন কর্মকর্তা",
    newApplication: "নতুন আবেদন",
    applicationStatus: "আবেদনের অবস্থা",
    startApplication: "আবেদন শুরু করুন",
    checkStatus: "অবস্থা পরীক্ষা করুন",
    backButton: "← ফিরে যান",
    citizenServices: "নাগরিক সেবা",
    availableSchemes: "উপলব্ধ প্রকল্প",
    applyNow: "এখনই আবেদন করুন",
    personalInfo: "ব্যক্তিগত তথ্য",
    additionalInfo: "অতিরিক্ত তথ্য",
    documents: "নথিপত্র",
    schemeSelection: "প্রকল্প নির্বাচন",
    fullName: "সম্পূর্ণ নাম",
    aadhaar: "আধার নম্বর",
    mobile: "মোবাইল নম্বর",
    email: "ইমেইল ঠিকানা",
    dob: "জন্ম তারিখ",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    fatherName: "পিতার নাম",
    caste: "জাতি",
    address: "সম্পূর্ণ ঠিকানা",
    village: "গ্রাম",
    district: "জেলা",
    state: "রাজ্য",
    pincode: "পিন কোড",
    uploadDocuments: "প্রয়োজনীয় নথি আপলোড করুন",
    selectSchemes: "প্রকল্প নির্বাচন করুন",
    submit: "জমা দিন",
    next: "পরবর্তী",
    previous: "পূর্ববর্তী",
    back: "ফিরে",
    applicationSubmitted: "আবেদন সফলভাবে জমা দেওয়া হয়েছে",
    yourApplicationId: "আপনার আবেদন নম্বর",
    keepThisId: "ভবিষ্যতের জন্য এই নম্বরটি নিরাপদে রাখুন",
    returnToDashboard: "ড্যাশবোর্ডে ফিরে যান",
    downloadReceipt: "রসিদ ডাউনলোড করুন",
    officerDashboard: "কর্মকর্তা ড্যাশবোর্ড",
    welcomeBack: "স্বাগতম, উপজাতীয় আবেদন এবং ভূমি রেকর্ড পরিচালনা করুন",
    generateReport: "রিপোর্ট তৈরি করুন",
    openMapView: "মানচিত্র দেখুন",
    pendingApplications: "অপেক্ষমাণ আবেদন",
    approvedThisMonth: "এই মাসে অনুমোদিত",
    rejectedApplications: "প্রত্যাখ্যাত আবেদন",
    landMarked: "ভূমি চিহ্নিত",
    applications: "আবেদন",
    analytics: "বিশ্লেষণ",
    landRecords: "ভূমি রেকর্ড",
    aiSupport: "AI সহায়তা",
    documentUpload: "নথি আপলোড",
    uploadFRADocuments: "FRA নথি আপলোড করুন",
    ocrExtraction: "OCR পাঠ্য নিষ্কাশন",
    aiDecisionSupport: "AI সিদ্ধান্ত সহায়তা ব্যবস্থা",
    exportReports: "রিপোর্ট রপ্তানি",
    extractText: "পাঠ্য নিষ্কাশন করুন",
    editText: "পাঠ্য সম্পাদনা করুন",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    exportPDF: "PDF রপ্তানি",
    exportExcel: "এক্সেল রপ্তানি",
    processingDocument: "নথি প্রক্রিয়াকরণ...",
    textExtracted: "পাঠ্য সফলভাবে নিষ্কাশিত",
    reviewAndEdit: "নিষ্কাশিত পাঠ্য পর্যালোচনা এবং সম্পাদনা করুন"
  },
  te: {
    title: "గిరిజన వ్యవహారాల పోర్టల్",
    subtitle: "భారత ప్రభుత్వం",
    citizen: "నేను పౌరుడను",
    officer: "నేను అధికారిని",
    newApplication: "కొత్త దరఖాస్తు",
    applicationStatus: "దరఖాస్తు స్థితి",
    startApplication: "దరఖాస్తు ప్రారంభించండి",
    checkStatus: "స్థితిని తనిఖీ చేయండి",
    backButton: "← వెనుకకు వెళ్ళండి",
    citizenServices: "పౌర సేవలు",
    availableSchemes: "అందుబాటులో ఉన్న పథకాలు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    personalInfo: "వ్యక్తిగత సమాచారం",
    additionalInfo: "అదనపు సమాచారం",
    documents: "పత్రాలు",
    schemeSelection: "పథకం ఎంపిక",
    fullName: "పూర్తి పేరు",
    aadhaar: "ఆధార్ నంబర్",
    mobile: "మొబైల్ నంబర్",
    email: "ఇమెయిల్ చిరునామా",
    dob: "పుట్టిన తేదీ",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    fatherName: "తండ్రి పేరు",
    caste: "కులం",
    address: "పూర్తి చిరునామా",
    village: "గ్రామం",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    pincode: "పిన్ కోడ్",
    uploadDocuments: "అవసరమైన పత్రాలను అప్‌లోడ్ చేయండి",
    selectSchemes: "పథకాలను ఎంచుకోండి",
    submit: "సమర్పించండి",
    next: "తరువాత",
    previous: "మునుపటి",
    back: "వెనుక",
    applicationSubmitted: "దరఖాస్తు విజయవంతంగా సమర్పించబడింది",
    yourApplicationId: "మీ దరఖాస్తు సంఖ్య",
    keepThisId: "భవిష్యత్ రిఫరెన్స్ కోసం ఈ సంఖ్యను భద్రంగా ఉంచండి",
    returnToDashboard: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
    downloadReceipt: "రసీదు డౌన్‌లోడ్ చేయండి",
    officerDashboard: "అధికారి డ్యాష్‌బోర్డ్",
    welcomeBack: "తిరిగి స్వాగతం, గిరిజన దరఖాస్తులు మరియు భూమి రికార్డులను నిర్వహించండి",
    generateReport: "నివేదిక రూపొందించండి",
    openMapView: "మ్యాప్ వ్యూ తెరవండి",
    pendingApplications: "పెండింగ్ దరఖాస్తులు",
    approvedThisMonth: "ఈ నెలలో ఆమోదించబడింది",
    rejectedApplications: "తిరస్కరించబడిన దరఖాస్తులు",
    landMarked: "భూమి గుర్తించబడింది",
    applications: "దరఖాస్తులు",
    analytics: "విశ్లేషణలు",
    landRecords: "భూమి రికార్డులు",
    aiSupport: "AI మద్దతు",
    documentUpload: "పత్రం అప్‌లోడ్",
    uploadFRADocuments: "FRA పత్రాలను అప్‌లోడ్ చేయండి",
    ocrExtraction: "OCR టెక్స్ట్ ఎక్స్‌ట్రాక్షన్",
    aiDecisionSupport: "AI నిర్ణయ మద్దతు వ్యవస్థ",
    exportReports: "నివేదికలను ఎగుమతి చేయండి",
    extractText: "టెక్స్ట్ ఎక్స్‌ట్రాక్ట్ చేయండి",
    editText: "టెక్స్ట్ సవరించండి",
    saveChanges: "మార్పులను సేవ్ చేయండి",
    exportPDF: "PDF ఎగుమతి",
    exportExcel: "ఎక్సెల్ ఎగుమతి",
    processingDocument: "పత్రం ప్రాసెసింగ్...",
    textExtracted: "టెక్స్ట్ విజయవంతంగా ఎక్స్‌ట్రాక్ట్ చేయబడింది",
    reviewAndEdit: "ఎక్స్‌ట్రాక్ట్ చేసిన టెక్స్ట్‌ను సమీక్షించండి మరియు సవరించండి"
  },
  or: {
    title: "ଆଦିବାସୀ ବ୍ୟାପାର ପୋର୍ଟାଲ",
    subtitle: "ଭାରତ ସରକାର",
    citizen: "ମୁଁ ଜଣେ ନାଗରିକ",
    officer: "ମୁଁ ଜଣେ ଅଧିକାରୀ",
    newApplication: "ନୂତନ ଆବେଦନ",
    applicationStatus: "ଆବେଦନର ସ୍ଥିତି",
    startApplication: "ଆବେଦନ ଆରମ୍ଭ କରନ୍ତୁ",
    checkStatus: "ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ",
    backButton: "← ପଛକୁ ଯାଆନ୍ତୁ",
    citizenServices: "ନାଗରିକ ସେବା",
    availableSchemes: "ଉପଲବ୍ଧ ଯୋଜନା",
    applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
    personalInfo: "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
    additionalInfo: "ଅତିରିକ୍ତ ସୂଚନା",
    documents: "ଦଲିଲପତ୍ର",
    schemeSelection: "ଯୋଜନା ଚୟନ",
    fullName: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    aadhaar: "ଆଧାର ନମ୍ବର",
    mobile: "ମୋବାଇଲ ନମ୍ବର",
    email: "ଇମେଇଲ ଠିକଣା",
    dob: "ଜନ୍ମ ତାରିଖ",
    gender: "ଲିଙ୍ଗ",
    male: "ପୁରୁଷ",
    female: "ମହିଳା",
    other: "ଅନ୍ୟାନ୍ୟ",
    fatherName: "ପିତାଙ୍କ ନାମ",
    caste: "ଜାତି",
    address: "ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା",
    village: "ଗାଁ",
    district: "ଜିଲ୍ଲା",
    state: "ରାଜ୍ୟ",
    pincode: "ପିନ କୋଡ",
    uploadDocuments: "ଆବଶ୍ୟକ ଦଲିଲପତ୍ର ଅପଲୋଡ କରନ୍ତୁ",
    selectSchemes: "ଯୋଜନା ଚୟନ କରନ୍ତୁ",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    next: "ପରବର୍ତ୍ତୀ",
    previous: "ପୂର୍ବବର୍ତ୍ତୀ",
    back: "ପଛ",
    applicationSubmitted: "ଆବେଦନ ସଫଳତାର ସହିତ ଦାଖଲ ହୋଇଛି",
    yourApplicationId: "ଆପଣଙ୍କର ଆବେଦନ ନମ୍ବର",
    keepThisId: "ଭବିଷ୍ୟତ ରେଫରେନ୍ସ ପାଇଁ ଏହି ନମ୍ବରକୁ ସୁରକ୍ଷିତ ରଖନ୍ତୁ",
    returnToDashboard: "ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ",
    downloadReceipt: "ରସିଦ ଡାଉନଲୋଡ କରନ୍ତୁ",
    officerDashboard: "ଅଧିକାରୀ ଡ୍ୟାସବୋର୍ଡ",
    welcomeBack: "ସ୍ୱାଗତ, ଆଦିବାସୀ ଆବେଦନ ଏବଂ ଜମି ରେକର୍ଡ ପରିଚାଳନା କରନ୍ତୁ",
    generateReport: "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
    openMapView: "ମାନଚିତ୍ର ଦେଖନ୍ତୁ",
    pendingApplications: "ପେଣ୍ଡିଂ ଆବେଦନ",
    approvedThisMonth: "ଏହି ମାସରେ ଅନୁମୋଦିତ",
    rejectedApplications: "ପ୍ରତ୍ୟାଖ୍ୟାନ ହୋଇଥିବା ଆବେଦନ",
    landMarked: "ଜମି ଚିହ୍ନିତ",
    applications: "ଆବେଦନଗୁଡ଼ିକ",
    analytics: "ବିଶ୍ଳେଷଣ",
    landRecords: "ଜମି ରେକର୍ଡ",
    aiSupport: "AI ସହାୟତା",
    documentUpload: "ଦଲିଲ ଅପଲୋଡ",
    uploadFRADocuments: "FRA ଦଲିଲ ଅପଲୋଡ କରନ୍ତୁ",
    ocrExtraction: "OCR ଟେକ୍ସଟ ନିଷ୍କାସନ",
    aiDecisionSupport: "AI ନିଷ୍ପତ୍ତି ସହାୟତା ବ୍ୟବସ୍ଥା",
    exportReports: "ରିପୋର୍ଟ ରପ୍ତାନି",
    extractText: "ଟେକ୍ସଟ ନିଷ୍କାସନ କରନ୍ତୁ",
    editText: "ଟେକ୍ସଟ ଏଡିଟ କରନ୍ତୁ",
    saveChanges: "ପରିବର୍ତ୍ତନ ସେଭ କରନ୍ତୁ",
    exportPDF: "PDF ରପ୍ତାନି",
    exportExcel: "ଏକ୍ସେଲ ରପ୍ତାନି",
    processingDocument: "ଦଲିଲ ପ୍ରକ୍ରିୟାକରଣ...",
    textExtracted: "ଟେକ୍ସଟ ସଫଳତାର ସହିତ ନିଷ୍କାସିତ",
    reviewAndEdit: "ନିଷ୍କାସିତ ଟେକ୍ସଟର ସମୀକ୍ଷା ଏବଂ ସମ୍ପାଦନା କରନ୍ତୁ"
  }
};

type Language = 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'te' | 'or';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('hi');

  const t = (key: TranslationKey): string => {
    // Ensure we have a valid language, fallback to 'hi' if not
    const validLanguage = translations[language] ? language : 'hi';
    return translations[validLanguage][key] || translations['hi'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Provide fallback values if context is not available
    return {
      language: 'hi' as Language,
      setLanguage: () => {},
      t: (key: TranslationKey) => translations.hi[key] || key
    };
  }
  return context;
};