// import { createContext, useContext, useState, ReactNode } from "react";

// const translations = {
//   en: {
//     title: "Tribal Affairs Portal",
//     subtitle: "Government of India",
//     citizen: "I am a Citizen",
//     officer: "I am an Officer",
//     newApplication: "New Application",
//     applicationStatus: "Application Status",
//     startApplication: "Start Application",
//     checkStatus: "Check Status",
//     backButton: "← Go Back",
//     citizenServices: "Citizen Services",
//     availableSchemes: "Available Schemes",
//     applyNow: "Apply Now",
//     personalInfo: "Personal Information",
//     additionalInfo: "Additional Information",
//     documents: "Documents",
//     schemeSelection: "Scheme Selection",
//     fullName: "Full Name",
//     aadhaar: "Aadhaar Number",
//     mobile: "Mobile Number",
//     email: "Email Address",
//     dob: "Date of Birth",
//     gender: "Gender",
//     male: "Male",
//     female: "Female",
//     other: "Other",
//     fatherName: "Father's Name",
//     caste: "Caste/Tribe",
//     address: "Complete Address",
//     village: "Village",
//     district: "District",
//     state: "State",
//     pincode: "Pin Code",
//     uploadDocuments: "Upload Required Documents",
//     selectSchemes: "Select Schemes",
//     submit: "Submit",
//     next: "Next",
//     previous: "Previous",
//     back: "Back",
//     applicationSubmitted: "Application Submitted Successfully",
//     yourApplicationId: "Your Application ID",
//     keepThisId: "Please keep this ID safe for future reference",
//     returnToDashboard: "Return to Dashboard",
//     downloadReceipt: "Download Receipt",
//     // Officer Dashboard
//     officerDashboard: "Officer Dashboard",
//     welcomeBack: "Welcome back, manage tribal applications and land records",
//     generateReport: "Generate Report",
//     openMapView: "Open Map View",
//     pendingApplications: "Pending Applications",
//     approvedThisMonth: "Approved This Month",
//     rejectedApplications: "Rejected Applications",
//     landMarked: "Land Marked",
//     applications: "Applications",
//     analytics: "Analytics",
//     landRecords: "Land Records",
//     aiSupport: "AI Support",
//     documentUpload: "Document Upload",
//     uploadFRADocuments: "Upload FRA Documents",
//     ocrExtraction: "OCR Text Extraction",
//     aiDecisionSupport: "AI Decision Support System",
//     exportReports: "Export Reports",
//     extractText: "Extract Text",
//     editText: "Edit Text",
//     saveChanges: "Save Changes",
//     exportPDF: "Export PDF",
//     exportExcel: "Export Excel",
//     processingDocument: "Processing document...",
//     textExtracted: "Text extracted successfully",
//     reviewAndEdit: "Review and edit extracted text"
//   },
//   hi: {
//     title: "जनजातीय मामले पोर्टल",
//     subtitle: "भारत सरकार",
//     citizen: "मैं नागरिक हूं",
//     officer: "मैं अधिकारी हूं",
//     newApplication: "नया आवेदन",
//     applicationStatus: "आवेदन की स्थिति",
//     startApplication: "आवेदन शुरू करें",
//     checkStatus: "स्थिति देखें",
//     backButton: "← वापस जाएं",
//     citizenServices: "नागरिक सेवाएं",
//     availableSchemes: "उपलब्ध योजनाएं",
//     applyNow: "आवेदन करें",
//     personalInfo: "व्यक्तिगत जानकारी",
//     additionalInfo: "पूरी जानकारी",
//     documents: "दस्तावेज अपलोड",
//     schemeSelection: "योजना चयन",
//     fullName: "पूरा नाम",
//     aadhaar: "आधार नंबर",
//     mobile: "मोबाइल नंबर",
//     email: "ईमेल पता",
//     dob: "जन्म तारीख",
//     gender: "लिंग",
//     male: "पुरुष",
//     female: "महिला",
//     other: "अन्य",
//     fatherName: "पिता का नाम",
//     caste: "जाति",
//     address: "पूरा पता",
//     village: "गांव",
//     district: "जिला",
//     state: "राज्य",
//     pincode: "पिन कोड",
//     uploadDocuments: "आवश्यक दस्तावेज अपलोड करें",
//     selectSchemes: "योजनाओं का चयन करें",
//     submit: "सबमिट करें",
//     next: "अगला",
//     previous: "पिछला",
//     back: "वापस",
//     applicationSubmitted: "आवेदन सफलतापूर्वक जमा हो गया",
//     yourApplicationId: "आपका आवेदन नंबर",
//     keepThisId: "कृपया इस नंबर को भविष्य के लिए संभाल कर रखें",
//     returnToDashboard: "डैशबोर्ड पर वापस जाएं",
//     downloadReceipt: "रसीद डाउनलोड करें",
//     // Officer Dashboard
//     officerDashboard: "अधिकारी डैशबोर्ड",
//     welcomeBack: "वापस स्वागत है, जनजातीय आवेदन और भूमि रिकॉर्ड प्रबंधित करें",
//     generateReport: "रिपोर्ट तैयार करें",
//     openMapView: "मानचित्र दृश्य खोलें",
//     pendingApplications: "लंबित आवेदन",
//     approvedThisMonth: "इस महीने स्वीकृत",
//     rejectedApplications: "अस्वीकृत आवेदन",
//     landMarked: "भूमि चिह्नित",
//     applications: "आवेदन",
//     analytics: "विश्लेषण",
//     landRecords: "भूमि रिकॉर्ड",
//     aiSupport: "AI सहायता",
//     documentUpload: "दस्तावेज़ अपलोड",
//     uploadFRADocuments: "FRA दस्तावेज़ अपलोड करें",
//     ocrExtraction: "OCR पाठ निष्कर्षण",
//     aiDecisionSupport: "AI निर्णय सहायता प्रणाली",
//     exportReports: "रिपोर्ट निर्यात",
//     extractText: "पाठ निकालें",
//     editText: "पाठ संपादित करें",
//     saveChanges: "परिवर्तन सहेजें",
//     exportPDF: "PDF निर्यात",
//     exportExcel: "एक्सेल निर्यात",
//     processingDocument: "दस्तावेज़ प्रसंस्करण...",
//     textExtracted: "पाठ सफलतापूर्वक निकाला गया",
//     reviewAndEdit: "निकाले गए पाठ की समीक्षा और संपादन करें"
//   },
//   mr: {
//     title: "आदिवासी व्यवहार पोर्टल",
//     subtitle: "भारत सरकार",
//     citizen: "मी नागरिक आहे",
//     officer: "मी अधिकारी आहे",
//     newApplication: "नवीन अर्ज",
//     applicationStatus: "अर्जाची स्थिती",
//     startApplication: "अर्ज सुरू करा",
//     checkStatus: "स्थिती तपासा",
//     backButton: "← परत जा",
//     citizenServices: "नागरिक सेवा",
//     availableSchemes: "उपलब्ध योजना",
//     applyNow: "आता अर्ज करा",
//     personalInfo: "वैयक्तिक माहिती",
//     additionalInfo: "अतिरिक्त माहिती",
//     documents: "कागदपत्रे",
//     schemeSelection: "योजना निवड",
//     fullName: "पूर्ण नाव",
//     aadhaar: "आधार क्रमांक",
//     mobile: "मोबाइल नंबर",
//     email: "ईमेल पत्ता",
//     dob: "जन्म तारीख",
//     gender: "लिंग",
//     male: "पुरुष",
//     female: "महिला",
//     other: "इतर",
//     fatherName: "वडिलांचे नाव",
//     caste: "जात",
//     address: "पूर्ण पत्ता",
//     village: "गाव",
//     district: "जिल्हा",
//     state: "राज्य",
//     pincode: "पिन कोड",
//     uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
//     selectSchemes: "योजना निवडा",
//     submit: "सबमिट करा",
//     next: "पुढे",
//     previous: "मागे",
//     back: "परत",
//     applicationSubmitted: "अर्ज यशस्वीरित्या सबमिट झाला",
//     yourApplicationId: "तुमचा अर्ज क्रमांक",
//     keepThisId: "कृपया हा क्रमांक भविष्यासाठी सुरक्षित ठेवा",
//     returnToDashboard: "डॅशबोर्डवर परत जा",
//     downloadReceipt: "रसीद डाउनलोड करा",
//     officerDashboard: "अधिकारी डॅशबोर्ड",
//     welcomeBack: "परत स्वागत, आदिवासी अर्ज आणि जमीन रेकॉर्ड व्यवस्थापित करा",
//     generateReport: "अहवाल तयार करा",
//     openMapView: "नकाशा दृश्य उघडा",
//     pendingApplications: "प्रलंबित अर्ज",
//     approvedThisMonth: "या महिन्यात मंजूर",
//     rejectedApplications: "नाकारलेले अर्ज",
//     landMarked: "जमीन चिन्हांकित",
//     applications: "अर्ज",
//     analytics: "विश्लेषण",
//     landRecords: "जमीन रेकॉर्ड",
//     aiSupport: "AI सहाय्य",
//     documentUpload: "दस्तऐवज अपलोड",
//     uploadFRADocuments: "FRA दस्तऐवज अपलोड करा",
//     ocrExtraction: "OCR मजकूर काढणे",
//     aiDecisionSupport: "AI निर्णय सहाय्य प्रणाली",
//     exportReports: "अहवाल निर्यात",
//     extractText: "मजकूर काढा",
//     editText: "मजकूर संपादित करा",
//     saveChanges: "बदल सेव्ह करा",
//     exportPDF: "PDF निर्यात",
//     exportExcel: "एक्सेल निर्यात",
//     processingDocument: "दस्तऐवज प्रक्रिया...",
//     textExtracted: "मजकूर यशस्वीरित्या काढला",
//     reviewAndEdit: "काढलेल्या मजकुराचे पुनरावलोकन आणि संपादन करा"
//   },
//   gu: {
//     title: "આદિવાસી બાબતોનું પોર્ટલ",
//     subtitle: "ભારત સરકાર",
//     citizen: "હું નાગરિક છું",
//     officer: "હું અધિકારી છું",
//     newApplication: "નવી અરજી",
//     applicationStatus: "અરજીની સ્થિતિ",
//     startApplication: "અરજી શરૂ કરો",
//     checkStatus: "સ્થિતિ તપાસો",
//     backButton: "← પાછા જાઓ",
//     citizenServices: "નાગરિક સેવાઓ",
//     availableSchemes: "ઉપલબ્ધ યોજનાઓ",
//     applyNow: "હવે અરજી કરો",
//     personalInfo: "વ્યક્તિગત માહિતી",
//     additionalInfo: "વધારાની માહિતી",
//     documents: "દસ્તાવેજો",
//     schemeSelection: "યોજના પસંદગી",
//     fullName: "પૂરું નામ",
//     aadhaar: "આધાર નંબર",
//     mobile: "મોબાઇલ નંબર",
//     email: "ઇમેઇલ સરનામું",
//     dob: "જન્મ તારીખ",
//     gender: "લિંગ",
//     male: "પુરુષ",
//     female: "સ્ત્રી",
//     other: "અન્ય",
//     fatherName: "પિતાનું નામ",
//     caste: "જાતિ",
//     address: "સંપૂર્ણ સરનામું",
//     village: "ગામ",
//     district: "જિલ્લો",
//     state: "રાજ્ય",
//     pincode: "પિન કોડ",
//     uploadDocuments: "જરૂરી દસ્તાવેજો અપલોડ કરો",
//     selectSchemes: "યોજનાઓ પસંદ કરો",
//     submit: "સબમિટ કરો",
//     next: "આગળ",
//     previous: "પાછળ",
//     back: "પાછા",
//     applicationSubmitted: "અરજી સફળતાપૂર્વક સબમિટ થઈ",
//     yourApplicationId: "તમારો અરજી નંબર",
//     keepThisId: "કૃપા કરીને આ નંબર ભવિષ્ય માટે સુરક્ષિત રાખો",
//     returnToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
//     downloadReceipt: "રસીદ ડાઉનલોડ કરો",
//     officerDashboard: "અધિકારી ડેશબોર્ડ",
//     welcomeBack: "પાછા સ્વાગત, આદિવાસી અરજીઓ અને જમીન રેકોર્ડનું સંચાલન કરો",
//     generateReport: "રિપોર્ટ જનરેટ કરો",
//     openMapView: "મેપ વ્યૂ ખોલો",
//     pendingApplications: "પેન્ડિંગ અરજીઓ",
//     approvedThisMonth: "આ મહિને મંજૂર",
//     rejectedApplications: "નકારેલી અરજીઓ",
//     landMarked: "જમીન ચિહ્નિત",
//     applications: "અરજીઓ",
//     analytics: "વિશ્લેષણ",
//     landRecords: "જમીન રેકોર્ડ",
//     aiSupport: "AI સહાય",
//     documentUpload: "દસ્તાવેજ અપલોડ",
//     uploadFRADocuments: "FRA દસ્તાવેજો અપલોડ કરો",
//     ocrExtraction: "OCR ટેક્સ્ટ એક્સટ્રેક્શન",
//     aiDecisionSupport: "AI ડિસિઝન સપોર્ટ સિસ્ટમ",
//     exportReports: "રિપોર્ટ્સ એક્સપોર્ટ",
//     extractText: "ટેક્સ્ટ એક્સટ્રેક્ટ કરો",
//     editText: "ટેક્સ્ટ એડિટ કરો",
//     saveChanges: "ચેન્જ સેવ કરો",
//     exportPDF: "PDF એક્સપોર્ટ",
//     exportExcel: "એક્સેલ એક્સપોર્ટ",
//     processingDocument: "દસ્તાવેજ પ્રોસેસિંગ...",
//     textExtracted: "ટેક્સ્ટ સફળતાપૂર્વક એક્સટ્રેક્ટ થયું",
//     reviewAndEdit: "એક્સટ્રેક્ટ થયેલા ટેક્સ્ટની સમીક્ષા અને સંપાદન કરો"
//   },
//   bn: {
//     title: "উপজাতীয় বিষয়ক পোর্টাল",
//     subtitle: "ভারত সরকার",
//     citizen: "আমি একজন নাগরিক",
//     officer: "আমি একজন কর্মকর্তা",
//     newApplication: "নতুন আবেদন",
//     applicationStatus: "আবেদনের অবস্থা",
//     startApplication: "আবেদন শুরু করুন",
//     checkStatus: "অবস্থা পরীক্ষা করুন",
//     backButton: "← ফিরে যান",
//     citizenServices: "নাগরিক সেবা",
//     availableSchemes: "উপলব্ধ প্রকল্প",
//     applyNow: "এখনই আবেদন করুন",
//     personalInfo: "ব্যক্তিগত তথ্য",
//     additionalInfo: "অতিরিক্ত তথ্য",
//     documents: "নথিপত্র",
//     schemeSelection: "প্রকল্প নির্বাচন",
//     fullName: "সম্পূর্ণ নাম",
//     aadhaar: "আধার নম্বর",
//     mobile: "মোবাইল নম্বর",
//     email: "ইমেইল ঠিকানা",
//     dob: "জন্ম তারিখ",
//     gender: "লিঙ্গ",
//     male: "পুরুষ",
//     female: "মহিলা",
//     other: "অন্যান্য",
//     fatherName: "পিতার নাম",
//     caste: "জাতি",
//     address: "সম্পূর্ণ ঠিকানা",
//     village: "গ্রাম",
//     district: "জেলা",
//     state: "রাজ্য",
//     pincode: "পিন কোড",
//     uploadDocuments: "প্রয়োজনীয় নথি আপলোড করুন",
//     selectSchemes: "প্রকল্প নির্বাচন করুন",
//     submit: "জমা দিন",
//     next: "পরবর্তী",
//     previous: "পূর্ববর্তী",
//     back: "ফিরে",
//     applicationSubmitted: "আবেদন সফলভাবে জমা দেওয়া হয়েছে",
//     yourApplicationId: "আপনার আবেদন নম্বর",
//     keepThisId: "ভবিষ্যতের জন্য এই নম্বরটি নিরাপদে রাখুন",
//     returnToDashboard: "ড্যাশবোর্ডে ফিরে যান",
//     downloadReceipt: "রসিদ ডাউনলোড করুন",
//     officerDashboard: "কর্মকর্তা ড্যাশবোর্ড",
//     welcomeBack: "স্বাগতম, উপজাতীয় আবেদন এবং ভূমি রেকর্ড পরিচালনা করুন",
//     generateReport: "রিপোর্ট তৈরি করুন",
//     openMapView: "মানচিত্র দেখুন",
//     pendingApplications: "অপেক্ষমাণ আবেদন",
//     approvedThisMonth: "এই মাসে অনুমোদিত",
//     rejectedApplications: "প্রত্যাখ্যাত আবেদন",
//     landMarked: "ভূমি চিহ্নিত",
//     applications: "আবেদন",
//     analytics: "বিশ্লেষণ",
//     landRecords: "ভূমি রেকর্ড",
//     aiSupport: "AI সহায়তা",
//     documentUpload: "নথি আপলোড",
//     uploadFRADocuments: "FRA নথি আপলোড করুন",
//     ocrExtraction: "OCR পাঠ্য নিষ্কাশন",
//     aiDecisionSupport: "AI সিদ্ধান্ত সহায়তা ব্যবস্থা",
//     exportReports: "রিপোর্ট রপ্তানি",
//     extractText: "পাঠ্য নিষ্কাশন করুন",
//     editText: "পাঠ্য সম্পাদনা করুন",
//     saveChanges: "পরিবর্তন সংরক্ষণ করুন",
//     exportPDF: "PDF রপ্তানি",
//     exportExcel: "এক্সেল রপ্তানি",
//     processingDocument: "নথি প্রক্রিয়াকরণ...",
//     textExtracted: "পাঠ্য সফলভাবে নিষ্কাশিত",
//     reviewAndEdit: "নিষ্কাশিত পাঠ্য পর্যালোচনা এবং সম্পাদনা করুন"
//   },
//   te: {
//     title: "గిరిజన వ్యవహారాల పోర్టల్",
//     subtitle: "భారత ప్రభుత్వం",
//     citizen: "నేను పౌరుడను",
//     officer: "నేను అధికారిని",
//     newApplication: "కొత్త దరఖాస్తు",
//     applicationStatus: "దరఖాస్తు స్థితి",
//     startApplication: "దరఖాస్తు ప్రారంభించండి",
//     checkStatus: "స్థితిని తనిఖీ చేయండి",
//     backButton: "← వెనుకకు వెళ్ళండి",
//     citizenServices: "పౌర సేవలు",
//     availableSchemes: "అందుబాటులో ఉన్న పథకాలు",
//     applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
//     personalInfo: "వ్యక్తిగత సమాచారం",
//     additionalInfo: "అదనపు సమాచారం",
//     documents: "పత్రాలు",
//     schemeSelection: "పథకం ఎంపిక",
//     fullName: "పూర్తి పేరు",
//     aadhaar: "ఆధార్ నంబర్",
//     mobile: "మొబైల్ నంబర్",
//     email: "ఇమెయిల్ చిరునామా",
//     dob: "పుట్టిన తేదీ",
//     gender: "లింగం",
//     male: "పురుషుడు",
//     female: "స్త్రీ",
//     other: "ఇతర",
//     fatherName: "తండ్రి పేరు",
//     caste: "కులం",
//     address: "పూర్తి చిరునామా",
//     village: "గ్రామం",
//     district: "జిల్లా",
//     state: "రాష్ట్రం",
//     pincode: "పిన్ కోడ్",
//     uploadDocuments: "అవసరమైన పత్రాలను అప్‌లోడ్ చేయండి",
//     selectSchemes: "పథకాలను ఎంచుకోండి",
//     submit: "సమర్పించండి",
//     next: "తరువాత",
//     previous: "మునుపటి",
//     back: "వెనుక",
//     applicationSubmitted: "దరఖాస్తు విజయవంతంగా సమర్పించబడింది",
//     yourApplicationId: "మీ దరఖాస్తు సంఖ్య",
//     keepThisId: "భవిష్యత్ రిఫరెన్స్ కోసం ఈ సంఖ్యను భద్రంగా ఉంచండి",
//     returnToDashboard: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
//     downloadReceipt: "రసీదు డౌన్‌లోడ్ చేయండి",
//     officerDashboard: "అధికారి డ్యాష్‌బోర్డ్",
//     welcomeBack: "తిరిగి స్వాగతం, గిరిజన దరఖాస్తులు మరియు భూమి రికార్డులను నిర్వహించండి",
//     generateReport: "నివేదిక రూపొందించండి",
//     openMapView: "మ్యాప్ వ్యూ తెరవండి",
//     pendingApplications: "పెండింగ్ దరఖాస్తులు",
//     approvedThisMonth: "ఈ నెలలో ఆమోదించబడింది",
//     rejectedApplications: "తిరస్కరించబడిన దరఖాస్తులు",
//     landMarked: "భూమి గుర్తించబడింది",
//     applications: "దరఖాస్తులు",
//     analytics: "విశ్లేషణలు",
//     landRecords: "భూమి రికార్డులు",
//     aiSupport: "AI మద్దతు",
//     documentUpload: "పత్రం అప్‌లోడ్",
//     uploadFRADocuments: "FRA పత్రాలను అప్‌లోడ్ చేయండి",
//     ocrExtraction: "OCR టెక్స్ట్ ఎక్స్‌ట్రాక్షన్",
//     aiDecisionSupport: "AI నిర్ణయ మద్దతు వ్యవస్థ",
//     exportReports: "నివేదికలను ఎగుమతి చేయండి",
//     extractText: "టెక్స్ట్ ఎక్స్‌ట్రాక్ట్ చేయండి",
//     editText: "టెక్స్ట్ సవరించండి",
//     saveChanges: "మార్పులను సేవ్ చేయండి",
//     exportPDF: "PDF ఎగుమతి",
//     exportExcel: "ఎక్సెల్ ఎగుమతి",
//     processingDocument: "పత్రం ప్రాసెసింగ్...",
//     textExtracted: "టెక్స్ట్ విజయవంతంగా ఎక్స్‌ట్రాక్ట్ చేయబడింది",
//     reviewAndEdit: "ఎక్స్‌ట్రాక్ట్ చేసిన టెక్స్ట్‌ను సమీక్షించండి మరియు సవరించండి"
//   },
//   or: {
//     title: "ଆଦିବାସୀ ବ୍ୟାପାର ପୋର୍ଟାଲ",
//     subtitle: "ଭାରତ ସରକାର",
//     citizen: "ମୁଁ ଜଣେ ନାଗରିକ",
//     officer: "ମୁଁ ଜଣେ ଅଧିକାରୀ",
//     newApplication: "ନୂତନ ଆବେଦନ",
//     applicationStatus: "ଆବେଦନର ସ୍ଥିତି",
//     startApplication: "ଆବେଦନ ଆରମ୍ଭ କରନ୍ତୁ",
//     checkStatus: "ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ",
//     backButton: "← ପଛକୁ ଯାଆନ୍ତୁ",
//     citizenServices: "ନାଗରିକ ସେବା",
//     availableSchemes: "ଉପଲବ୍ଧ ଯୋଜନା",
//     applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
//     personalInfo: "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
//     additionalInfo: "ଅତିରିକ୍ତ ସୂଚନା",
//     documents: "ଦଲିଲପତ୍ର",
//     schemeSelection: "ଯୋଜନା ଚୟନ",
//     fullName: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
//     aadhaar: "ଆଧାର ନମ୍ବର",
//     mobile: "ମୋବାଇଲ ନମ୍ବର",
//     email: "ଇମେଇଲ ଠିକଣା",
//     dob: "ଜନ୍ମ ତାରିଖ",
//     gender: "ଲିଙ୍ଗ",
//     male: "ପୁରୁଷ",
//     female: "ମହିଳା",
//     other: "ଅନ୍ୟାନ୍ୟ",
//     fatherName: "ପିତାଙ୍କ ନାମ",
//     caste: "ଜାତି",
//     address: "ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା",
//     village: "ଗାଁ",
//     district: "ଜିଲ୍ଲା",
//     state: "ରାଜ୍ୟ",
//     pincode: "ପିନ କୋଡ",
//     uploadDocuments: "ଆବଶ୍ୟକ ଦଲିଲପତ୍ର ଅପଲୋଡ କରନ୍ତୁ",
//     selectSchemes: "ଯୋଜନା ଚୟନ କରନ୍ତୁ",
//     submit: "ଦାଖଲ କରନ୍ତୁ",
//     next: "ପରବର୍ତ୍ତୀ",
//     previous: "ପୂର୍ବବର୍ତ୍ତୀ",
//     back: "ପଛ",
//     applicationSubmitted: "ଆବେଦନ ସଫଳତାର ସହିତ ଦାଖଲ ହୋଇଛି",
//     yourApplicationId: "ଆପଣଙ୍କର ଆବେଦନ ନମ୍ବର",
//     keepThisId: "ଭବିଷ୍ୟତ ରେଫରେନ୍ସ ପାଇଁ ଏହି ନମ୍ବରକୁ ସୁରକ୍ଷିତ ରଖନ୍ତୁ",
//     returnToDashboard: "ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ",
//     downloadReceipt: "ରସିଦ ଡାଉନଲୋଡ କରନ୍ତୁ",
//     officerDashboard: "ଅଧିକାରୀ ଡ୍ୟାସବୋର୍ଡ",
//     welcomeBack: "ସ୍ୱାଗତ, ଆଦିବାସୀ ଆବେଦନ ଏବଂ ଜମି ରେକର୍ଡ ପରିଚାଳନା କରନ୍ତୁ",
//     generateReport: "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
//     openMapView: "ମାନଚିତ୍ର ଦେଖନ୍ତୁ",
//     pendingApplications: "ପେଣ୍ଡିଂ ଆବେଦନ",
//     approvedThisMonth: "ଏହି ମାସରେ ଅନୁମୋଦିତ",
//     rejectedApplications: "ପ୍ରତ୍ୟାଖ୍ୟାନ ହୋଇଥିବା ଆବେଦନ",
//     landMarked: "ଜମି ଚିହ୍ନିତ",
//     applications: "ଆବେଦନଗୁଡ଼ିକ",
//     analytics: "ବିଶ୍ଳେଷଣ",
//     landRecords: "ଜମି ରେକର୍ଡ",
//     aiSupport: "AI ସହାୟତା",
//     documentUpload: "ଦଲିଲ ଅପଲୋଡ",
//     uploadFRADocuments: "FRA ଦଲିଲ ଅପଲୋଡ କରନ୍ତୁ",
//     ocrExtraction: "OCR ଟେକ୍ସଟ ନିଷ୍କାସନ",
//     aiDecisionSupport: "AI ନିଷ୍ପତ୍ତି ସହାୟତା ବ୍ୟବସ୍ଥା",
//     exportReports: "ରିପୋର୍ଟ ରପ୍ତାନି",
//     extractText: "ଟେକ୍ସଟ ନିଷ୍କାସନ କରନ୍ତୁ",
//     editText: "ଟେକ୍ସଟ ଏଡିଟ କରନ୍ତୁ",
//     saveChanges: "ପରିବର୍ତ୍ତନ ସେଭ କରନ୍ତୁ",
//     exportPDF: "PDF ରପ୍ତାନି",
//     exportExcel: "ଏକ୍ସେଲ ରପ୍ତାନି",
//     processingDocument: "ଦଲିଲ ପ୍ରକ୍ରିୟାକରଣ...",
//     textExtracted: "ଟେକ୍ସଟ ସଫଳତାର ସହିତ ନିଷ୍କାସିତ",
//     reviewAndEdit: "ନିଷ୍କାସିତ ଟେକ୍ସଟର ସମୀକ୍ଷା ଏବଂ ସମ୍ପାଦନା କରନ୍ତୁ"
//   }
// };

// type Language = 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'te' | 'or';
// type TranslationKey = keyof typeof translations.en;

// interface LanguageContextType {
//   language: Language;
//   setLanguage: (lang: Language) => void;
//   t: (key: TranslationKey) => string;
// }

// const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// export const LanguageProvider = ({ children }: { children: ReactNode }) => {
//   const [language, setLanguage] = useState<Language>('hi');

//   const t = (key: TranslationKey): string => {
//     // Ensure we have a valid language, fallback to 'hi' if not
//     const validLanguage = translations[language] ? language : 'hi';
//     return translations[validLanguage][key] || translations['hi'][key] || key;
//   };

//   return (
//     <LanguageContext.Provider value={{ language, setLanguage, t }}>
//       {children}
//     </LanguageContext.Provider>
//   );
// };

// export const useLanguage = () => {
//   const context = useContext(LanguageContext);
//   if (context === undefined) {
//     // Provide fallback values if context is not available
//     return {
//       language: 'hi' as Language,
//       setLanguage: () => {},
//       t: (key: TranslationKey) => translations.hi[key] || key
//     };
//   }
//   return context;
// };


import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'hi' | 'en' | 'od' | 'te' | 'bn' | 'ta' | 'ml' | 'kn' | 'gu' | 'mr' | 'pa' | 'as' | 'ur' | 'sd' | 'ks' | 'ne' | 'bo' | 'kok' | 'mni' | 'sat' | 'doi' | 'mai';

interface LanguageContextType {
  currentLanguage: Language;
  setCurrentLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface Translations {
  [key: string]: {
    [K in Language]: string;
  };
}

const translations: Translations = {
  // Header
  'header.title': {
    hi: 'जनजातीय मामले पोर्टल',
    en: 'Tribal Affairs Portal',
    od: 'ଆଦିବାସୀ ବିଷୟ ପୋର୍ଟାଲ',
    te: 'గిరిజన వ్యవహారాల పోర్టల్',
    bn: 'উপজাতীয় বিষয়ক পোর্টাল',
    ta: 'பழங்குடியினர் விவகார போர்டல்',
    ml: 'ഗോത്രവർഗ കാര്യ പോർട്ടൽ',
    kn: 'ಬುಡಕಟ್ಟು ವ್ಯವಹಾರಗಳ ಪೋರ್ಟಲ್',
    gu: 'આદિવાસી બાબતોનું પોર્ટલ',
    mr: 'आदिवासी घडामोडींचे पोर्टल',
    pa: 'ਆਦਿਵਾਸੀ ਮਾਮਲਿਆਂ ਦਾ ਪੋਰਟਲ',
    as: 'জনজাতীয় বিষয়ৰ পৰ্টেল',
    ur: 'قبائلی امور پورٹل',
    sd: 'قبائلي معاملن جو پورٽل',
    ks: 'قبائلی معاملات پورٹل',
    ne: 'आदिवासी मामिला पोर्टल',
    bo: 'མི་རིགས་གནས་ཚུལ་པོར་ཊལ།',
    kok: 'आदिवासी मामले पोर्टल',
    mni: 'ত্রিবাল অ্যাফেয়ার্স পোর্টাল',
    sat: 'ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱠᱟᱹᱢᱤ ᱯᱚᱨᱴᱟᱞ',
    doi: 'आदिवासी मामले पोर्टल',
    mai: 'आदिवासी मामला पोर्टल'
  },
  'header.subtitle': {
    hi: 'भारत सरकार',
    en: 'Government of India',
    od: 'ଭାରତ ସରକାର',
    te: 'భారత ప్రభుత్వం',
    bn: 'ভারত সরকার',
    ta: 'இந்திய அரசு',
    ml: 'ഇന്ത്യാ ഗവൺമെന്റ്',
    kn: 'ಭಾರತ ಸರ್ಕಾರ',
    gu: 'ભારત સરકાર',
    mr: 'भारत सरकार',
    pa: 'ਭਾਰਤ ਸਰਕਾਰ',
    as: 'ভাৰত চৰকাৰ',
    ur: 'حکومت ہند',
    sd: 'هندستان جي حڪومت',
    ks: 'ہندوستان حکومت',
    ne: 'भारत सरकार',
    bo: 'རྒྱ་གར་ཞིང་ཁབ།',
    kok: 'भारत सरकार',
    mni: 'ভারত সরকার',
    sat: 'ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ',
    doi: 'भारत सरकार',
    mai: 'भारत सरकार'
  },
  'header.citizen': {
    hi: 'नागरिक',
    en: 'Citizen',
    od: 'ନାଗରିକ',
    te: 'పౌరుడు',
    bn: 'নাগরিক',
    ta: 'குடிமகன்',
    ml: 'പൗരൻ',
    kn: 'ನಾಗರಿಕ',
    gu: 'નાગરિક',
    mr: 'नागरिक',
    pa: 'ਨਾਗਰਿਕ',
    as: 'নাগৰিক',
    ur: 'شہری',
    sd: 'شهري',
    ks: 'شہری',
    ne: 'नागरिक',
    bo: 'མི་སེར།',
    kok: 'नागरिक',
    mni: 'নাগরিক',
    sat: 'ᱫᱟᱬᱟᱱᱤᱭᱟᱹ',
    doi: 'नागरिक',
    mai: 'नागरिक'
  },
  'header.officer': {
    hi: 'अधिकारी',
    en: 'Officer',
    od: 'ଅଧିକାରୀ',
    te: 'అధికారి',
    bn: 'কর্মকর্তা',
    ta: 'அதிகாரி',
    ml: 'ഉദ്യോഗസ്ഥൻ',
    kn: 'ಅಧಿಕಾರಿ',
    gu: 'અધિકારી',
    mr: 'अधिकारी',
    pa: 'ਅਧਿਕਾਰੀ',
    as: 'বিষয়া',
    ur: 'افسر',
    sd: 'آفيسر',
    ks: 'آفیسر',
    ne: 'अधिकारी',
    bo: 'བྷེ་པོ།',
    kok: 'अधिकारी',
    mni: 'কর্মকর্তা',
    sat: 'ᱚᱯᱷᱤᱥᱚᱨ',
    doi: 'अधिकारी',
    mai: 'अधिकारी'
  },

  // Navigation
  'nav.apply': {
    hi: 'लाभ के लिए आवेदन करें',
    en: 'Apply for Benefits',
    od: 'ସୁବିଧା ପାଇଁ ଆବେଦନ କରନ୍ତୁ',
    te: 'ప్రయోజనాల కోసం దరఖాస్తు చేయండి',
    bn: 'সুবিধার জন্য আবেদন করুন',
    ta: 'நன்மைகளுக்கு விண்ணப்பிக்கவும்',
    ml: 'ആനുകൂല്യങ്ങൾക്കായി അപേക്ഷിക്കുക',
    kn: 'ಪ್ರಯೋಜನಗಳಿಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    gu: 'લાભો માટે અરજી કરો',
    mr: 'फायद्यांसाठी अर्ज करा',
    pa: 'ਲਾਭਾਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    as: 'সুবিধাৰ বাবে আবেদন কৰক',
    ur: 'فوائد کے لیے درخواست دیں',
    sd: 'فائدن لاءِ درخواست ڏيو',
    ks: 'فوائد کے لیے درخواست دیں',
    ne: 'लाभको लागि आवेदन गर्नुहोस्',
    bo: 'ཕན་ཐོགས་ཀྱི་ཞུ་བ་བྱེད།',
    kok: 'लाभ के लिए अर्जी करा',
    mni: 'সুবিধার জন্য আবেদন করুন',
    sat: 'ᱞᱟᱵᱷ ᱞᱟᱹᱜᱤᱫ ᱱᱮᱵᱮᱫᱚᱱ ᱢᱮ',
    doi: 'लाभ के लिए आवेदन करेयो',
    mai: 'लाभक लेल आवेदन करू'
  },
  'nav.status': {
    hi: 'स्थिति जांचें',
    en: 'Check Status',
    od: 'ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ',
    te: 'స్థితిని తనిఖీ చేయండి',
    bn: 'অবস্থা পরীক্ষা করুন',
    ta: 'நிலையை சரிபார்க்கவும்',
    ml: 'സ്ഥിതി പരിശോധിക്കുക',
    kn: 'ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    gu: 'સ્થિતિ તપાસો',
    mr: 'स्थिती तपासा',
    pa: 'ਸਥਿਤੀ ਜਾਂਚੋ',
    as: 'অৱস্থা পৰীক্ষা কৰক',
    ur: 'صورتحال چیک کریں',
    sd: 'صورتحال چيڪ ڪريو',
    ks: 'حالت چیک کریں',
    ne: 'स्थिति जाँच गर्नुहोस्',
    bo: 'གནས་ཚུལ་ལ་ལྟ།',
    kok: 'स्थिति पळेयात',
    mni: 'অবস্থা চেক করুন',
    sat: 'ᱚᱵᱚᱥᱛᱷᱟ ᱵᱟᱰᱟᱭᱢᱮ',
    doi: 'स्थिति देखेयो',
    mai: 'स्थिति देखू'
  },
  'nav.map': {
    hi: 'भूमि रिकॉर्ड',
    en: 'Land Records',
    od: 'ଜମି ରେକର୍ଡ',
    te: 'భూమి రికార్డులు',
    bn: 'ভূমি রেকর্ড',
    ta: 'நில பதிவுகள்',
    ml: 'ഭൂമി രേഖകൾ',
    kn: 'ಭೂಮಿ ದಾಖಲೆಗಳು',
    gu: 'જમીન રેકોર્ડ્સ',
    mr: 'जमीन रेकॉर्ड',
    pa: 'ਜ਼ਮੀਨ ਰਿਕਾਰਡ',
    as: 'ভূমি ৰেকৰ্ড',
    ur: 'زمینی ریکارڈز',
    sd: 'زمين جا رڪارڊ',
    ks: 'زمین ریکارڈ',
    ne: 'जग्गा रेकर्ड',
    bo: 'ས་ཆ་ཡིག་ཆ།',
    kok: 'जमीन रेकॉर्ड',
    mni: 'মাটির রেকর্ড',
    sat: 'ᱚᱛ ᱨᱮᱠᱚᱨᱰ',
    doi: 'जमीन रेकॉर्ड',
    mai: 'जमीन रेकर्ड'
  },
  'nav.dashboard': {
    hi: 'डैशबोर्ड',
    en: 'Dashboard',
    od: 'ଡ୍ୟାସବୋର୍ଡ',
    te: 'డాష్‌బోర్డ్',
    bn: 'ড্যাশবোর্ড',
    ta: 'டாஷ்போர்டு',
    ml: 'ഡാഷ്ബോർഡ്',
    kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    gu: 'ડેશબોર્ડ',
    mr: 'डॅशबोर्ड',
    pa: 'ਡੈਸ਼ਬੋਰਡ',
    as: 'ডেছব\'ৰ্ড',
    ur: 'ڈیش بورڈ',
    sd: 'ڊيش بورڊ',
    ks: 'ڈیش بورڈ',
    ne: 'ड्यासबोर्ड',
    bo: 'དབང་སྒྱུར་ལམ་སྟོན།',
    kok: 'डैशबोर्ड',
    mni: 'ড্যাশবোর্ড',
    sat: 'ᱰᱟᱥᱵᱚᱨᱰ',
    doi: 'डैशबोर्ड',
    mai: 'डैशबोर्ड'
  },
  'nav.approved_lands': {
    hi: 'अनुमोदित भूमि',
    en: 'Approved Lands',
    od: 'ଅନୁମୋଦିତ ଜମି',
    te: 'ఆమోదించిన భూములు',
    bn: 'অনুমোদিত ভূমি',
    ta: 'அங்கீகரிக்கப்பட்ட நிலங்கள்',
    ml: 'അംഗീകൃത ഭൂമി',
    kn: 'ಅನುಮೋದಿತ ಭೂಮಿ',
    gu: 'મંજૂર જમીનો',
    mr: 'मंजूर जमिनी',
    pa: 'ਮਨਜ਼ੂਰ ਜ਼ਮੀਨਾਂ',
    as: 'অনুমোদিত ভূমি',
    ur: 'منظور شدہ اراضی',
    sd: 'منظور ٿيل زمينون',
    ks: 'منظور شدہ زمینیں',
    ne: 'अनुमोदित जग्गाहरू',
    bo: 'གནང་བའི་ས་ཆ།',
    kok: 'मंजूर जमिनी',
    mni: 'অনুমোদিত ভূমি',
    sat: 'ᱢᱟᱱᱡᱩᱨ ᱟᱠᱟᱱ ᱚᱛ',
    doi: 'मंजूर जमीनां',
    mai: 'मंजूर जमीन'
  },

  // Hero Section
  'hero.badge': {
    hi: 'भारत सरकार की पहल',
    en: 'Government of India Initiative',
    od: 'ଭାରତ ସରକାରଙ୍କ ପଦକ୍ଷେପ',
    te: 'భారత ప్రభుత్వ చొరవ',
    bn: 'ভারত সরকারের উদ্যোগ',
    ta: 'இந்திய அரசின் முயற்சி',
    ml: 'ഇന്ത്യാ ഗവൺമെന്റ് സംരംഭം',
    kn: 'ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮ',
    gu: 'ભારત સરકારની પહેલ',
    mr: 'भारत सरकारचा उपक्रम',
    pa: 'ਭਾਰਤ ਸਰਕਾਰ ਦੀ ਪਹਿਲਕਦਮੀ',
    as: 'ভাৰত চৰকাৰৰ পদক্ষেপ',
    ur: 'حکومت ہند کی اقدام',
    sd: 'هندستان حڪومت جي اقدام',
    ks: 'حکومت ہند کی اقدام',
    ne: 'भारत सरकारको पहल',
    bo: 'རྒྱ་གར་ཞིང་ཁབ་ཀྱི་འཆར་གཞི།',
    kok: 'भारत सरकारची सुरुवात',
    mni: 'ভারত সরকারের উদ্যোগ',
    sat: 'ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ ᱟᱜ ᱮᱛᱦᱚᱵ',
    doi: 'भारत सरकार दी पहल',
    mai: 'भारत सरकारक पहल'
  },
  'hero.title_part1': {
    hi: 'जनजातीय मामले',
    en: 'Tribal Affairs',
    od: 'ଆଦିବାସୀ ବିଷୟ',
    te: 'గిరిజన వ్యవహారాలు',
    bn: 'উপজাতীয় বিষয়াবলি',
    ta: 'பழங்குடியினர் விவகாரங்கள்',
    ml: 'ഗോത്രവർഗ കാര്യങ്ങൾ',
    kn: 'ಬುಡಕಟ್ಟು ವ್ಯವಹಾರಗಳು',
    gu: 'આદિવાસી બાબતો',
    mr: 'आदिवासी घडामोडी',
    pa: 'ਆਦਿਵਾਸੀ ਮਾਮਲੇ',
    as: 'জনজাতীয় বিষয়',
    ur: 'قبائلی معاملات',
    sd: 'قبائلي معاملا',
    ks: 'قبائلی معاملات',
    ne: 'आदिवासी मामिला',
    bo: 'མི་རིགས་གནས་ཚུལ།',
    kok: 'आदिवासी मामले',
    mni: 'ত্রিবাল অ্যাফেয়ার্স',
    sat: 'ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱠᱟᱹᱢᱤ',
    doi: 'आदिवासी मामले',
    mai: 'आदिवासी मामला'
  },
  'hero.title_part2': {
    hi: 'डिजिटल पोर्टल',
    en: 'Digital Portal',
    od: 'ଡିଜିଟାଲ୍ ପୋର୍ଟାଲ',
    te: 'డిజిటల్ పోర్టల్',
    bn: 'ডিজিটাল পোর্টাল',
    ta: 'டிஜிட்டல் போர்டல்',
    ml: 'ഡിജിറ്റൽ പോർട്ടൽ',
    kn: 'ಡಿಜಿಟಲ್ ಪೋರ್ಟಲ್',
    gu: 'ડિજિટલ પોર્ટલ',
    mr: 'डिजिटल पोर्टल',
    pa: 'ਡਿਜਿਟਲ ਪੋਰਟਲ',
    as: 'ডিজিটেল পৰ্টেল',
    ur: 'ڈیجیٹل پورٹل',
    sd: 'ڊجيٽل پورٽل',
    ks: 'ڈیجیٹل پورٹل',
    ne: 'डिजिटल पोर्टल',
    bo: 'གློག་རིས་སྒོ་ལམ།',
    kok: 'डिजिटल पोर्टल',
    mni: 'ডিজিটাল পোর্টাল',
    sat: 'ᱰᱤᱡᱤᱴᱟᱞ ᱯᱚᱨᱴᱟᱞ',
    doi: 'डिजिटल पोर्टल',
    mai: 'डिजिटल पोर्टल'
  },
  'hero.description': {
    hi: 'डिजिटल गवर्नेंस के माध्यम से जनजातीय समुदायों को सशक्त बनाना। भूमि अधिकार, सरकारी लाभ के लिए आवेदन करें और अपने आवेदन को सहजता से ट्रैक करें।',
    en: 'Empowering tribal communities through digital governance. Apply for land rights, government benefits, and track your applications seamlessly.',
    od: 'ଡିଜିଟାଲ୍ ଶାସନ ମାଧ୍ୟମରେ ଆଦିବାସୀ ସମ୍ପ୍ରଦାୟକୁ ସଶକ୍ତ କରିବା। ଜମି ଅଧିକାର, ସରକାରୀ ସୁବିଧା ପାଇଁ ଆବେଦନ କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କର ଆବେଦନକୁ ସହଜରେ ଟ୍ରାକ୍ କରନ୍ତୁ।',
    te: 'డిజిటల్ పాలన ద్వారా గిరిజన సమాజాలను శక్తివంతం చేయడం. భూమి హక్కులు, ప్రభుత్వ ప్రయోజనాల కోసం దరఖాస్తు చేసుకోండి మరియు మీ దరఖాస్తులను సజావుగా ట్రాక్ చేయండి।',
    bn: 'ডিজিটাল শাসনের মাধ্যমে উপজাতীয় সম্প্রদায়ের ক্ষমতায়ন। ভূমি অধিকার, সরকারি সুবিধার জন্য আবেদন করুন এবং আপনার আবেদনগুলি নির্বিঘ্নে ট্র্যাক করুন।',
    ta: 'டிஜிட்டல் ஆட்சி மூலம் பழங்குடியின சமூகங்களை வலுப்படுத்துதல். நில உரிமைகள், அரசாங்க நலன்களுக்கு விண்ணப்பிக்கவும் மற்றும் உங்கள் விண்ணப்பங்களை தடையின்றி கண்காணிக்கவும்।',
    ml: 'ഡിജിറ്റൽ ഗവേണൻസിലൂടെ ഗോത്രവർഗ സമൂഹങ്ങളെ ശാക്തീകരിക്കുക. ഭൂമി അവകാശങ്ങൾ, സർക്കാർ ആനുകൂല്യങ്ങൾക്കായി അപേക്ഷിക്കുകയും നിങ്ങളുടെ അപേക്ഷകൾ തടസ്സമില്ലാതെ ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക।',
    kn: 'ಡಿಜಿಟಲ್ ಆಡಳಿತದ ಮೂಲಕ ಬುಡಕಟ್ಟು ಸಮುದಾಯಗಳನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು. ಭೂಮಿ ಹಕ್ಕುಗಳು, ಸರ್ಕಾರಿ ಪ್ರಯೋಜನಗಳಿಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಅರ್ಜಿಗಳನ್ನು ತಡೆರಹಿತವಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ।',
    gu: 'ડિજિટલ ગવર્નન્સ દ્વારા આદિવાસી સમુદાયોને સશક્ત બનાવવું. જમીન અધિકારો, સરકારી લાભો માટે અરજી કરો અને તમારી અરજીઓને સહેલાઈથી ટ્રેક કરો।',
    mr: 'डिजिटल शासनाद्वारे आदिवासी समुदायांना सक्षम करणे. जमीन हक्क, सरकारी फायद्यांसाठी अर्ज करा आणि तुमच्या अर्जांचा सहजतेने मागोवा घ्या।',
    pa: 'ਡਿਜਿਟਲ ਗਵਰਨੈਂਸ ਰਾਹੀਂ ਆਦਿਵਾਸੀ ਭਾਈਚਾਰਿਆਂ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ। ਜ਼ਮੀਨ ਦੇ ਅਧਿਕਾਰ, ਸਰਕਾਰੀ ਲਾਭਾਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ ਅਤੇ ਆਪਣੀਆਂ ਅਰਜ਼ੀਆਂ ਨੂੰ ਆਸਾਨੀ ਨਾਲ ਟ੍ਰੈਕ ਕਰੋ।',
    as: 'ডিজিটেল শাসনৰ জৰিয়তে জনজাতীয় সম্প্ৰদায়সমূহক সবলীকৰণ। ভূমি অধিকাৰ, চৰকাৰী সুবিধাৰ বাবে আবেদন কৰক আৰু আপোনাৰ আবেদনসমূহ নিৰবচ্ছিন্নভাৱে ট্ৰেক কৰক।',
    ur: 'ڈیجیٹل گورننس کے ذریعے قبائلی کمیونٹیز کو بااختیار بنانا۔ زمینی حقوق، حکومتی فوائد کے لیے درخواست دیں اور اپنی درخواستوں کو آسانی سے ٹریک کریں۔',
    sd: 'ڊجيٽل گورننس ذريعي قبائلي برادرين کي بااختيار بڻائڻ. زمين جا حق، حڪومتي فائدا لاءِ درخواست ڏيو ۽ پنهنجي درخواستن کي آساني سان ٽريڪ ڪريو.',
    ks: 'ڈیجیٹل گورننس کے ذریعے قبائلی کمیونٹیز کو بااختیار بنانا۔ زمینی حقوق، حکومتی فوائد کے لیے درخواست دیں اور اپنی درخواستوں کو آسانی سے ٹریک کریں۔',
    ne: 'डिजिटल शासनको माध्यमबाट आदिवासी समुदायहरूलाई सशक्त बनाउने। जग्गा अधिकार, सरकारी फाइदाहरूको लागि आवेदन दिनुहोस् र आफ्ना आवेदनहरूलाई सजिलैसँग ट्र्याक गर्नुहोस्।',
    bo: 'གློག་རིས་གཞུང་སྐྱོང་གི་ལམ་ནས་མི་རིགས་ཚོགས་སྡེ་ལ་དབང་ཆ་སྤྲོད་པ། ས་ཆའི་ཐོབ་ཐང་དང་གཞུང་གི་ཕན་ཐོགས་ཀྱི་ཞུ་བ་འབུལ་ཞིང་མགྱོགས་པོར་ལྟ།',
    kok: 'डिजिटल शासनाद्वारे आदिवासी समुदायांक सक्षम करप। जमीन हक्क, सरकारी फायदे खातीर अर्ज करात अनी तुमच्या अर्जांचो सहजतेन मागोवो घेयात।',
    mni: 'ডিজিটাল গভর্নেন্সের মাধ্যমে উপজাতীয় সম্প্রদায়ের ক্ষমতায়ন। ভূমি অধিকার, সরকারি সুবিধার জন্য আবেদন করুন এবং আপনার আবেদনগুলি নির্বিঘ্নে ট্র্যাক করুন।',
    sat: 'ᱰᱤᱡᱤᱴᱟᱞ ᱥᱟᱥᱚᱱ ᱛᱮ ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱦᱚᱲ ᱠᱚ ᱵᱟᱲᱟᱜ ᱠᱚᱣᱟ᱾ ᱚᱛ ᱟᱹᱫᱷᱟᱨ, ᱥᱚᱨᱠᱟᱨᱤ ᱞᱟᱵᱷ ᱞᱟᱹᱜᱤᱫ ᱱᱮᱵᱮᱫᱚᱱ ᱢᱮ ᱟᱨ ᱥᱟᱦᱟᱸ ᱛᱮ ᱴᱨᱮᱠ ᱢᱮ᱾',
    doi: 'डिजिटल शासन दे जरिये आदिवासी समुदायां गी सशक्त बनाना। जमीन दे हक्क, सरकारी फायदे आस्तै अर्जी दियो ते अपणी अर्जियां गी आसानी कन्ने ट्रैक करो।',
    mai: 'डिजिटल शासनक माध्यमसँ आदिवासी समुदायसभकेँ सशक्त बनाबै। जमीनक अधिकार, सरकारी लाभक लेल आवेदन दिअ आ अपन आवेदनसभकेँ सहजतासँ ट्रैक करू।'
  },
  'hero.citizen_button': {
    hi: 'मैं एक नागरिक हूं',
    en: "I'm a Citizen",
    od: 'ମୁଁ ଜଣେ ନାଗରିକ',
    te: 'నేను ఒక పౌరుడను',
    bn: 'আমি একজন নাগরিক',
    ta: 'நான் ஒரு குடிமகன்',
    ml: 'ഞാൻ ഒരു പൗരനാണ്',
    kn: 'ನಾನು ಒಬ್ಬ ನಾಗರಿಕ',
    gu: 'હું એક નાગરિક છું',
    mr: 'मी एक नागरिक आहे',
    pa: 'ਮੈਂ ਇੱਕ ਨਾਗਰਿਕ ਹਾਂ',
    as: 'মই এজন নাগৰিক',
    ur: 'میں ایک شہری ہوں',
    sd: 'مان هڪ شهري آهيان',
    ks: 'میں ایک شہری ہوں',
    ne: 'म एक नागरिक हुं',
    bo: 'ང་མི་སེར་ཞིག་ཡིན།',
    kok: 'हांव एक नागरिक',
    mni: 'ঐ অমা নাগরিক অমনি',
    sat: 'ᱤᱧ ᱫᱚ ᱢᱤᱫ ᱫᱟᱬᱟᱱᱤᱭᱟᱹ ᱠᱟᱱᱟᱧ',
    doi: 'मैं इक्क नागरिक आं',
    mai: 'हम एक नागरिक छी'
  },
  'hero.officer_button': {
    hi: 'मैं एक अधिकारी हूं',
    en: "I'm an Officer",
    od: 'ମୁଁ ଜଣେ ଅଧିକାରୀ',
    te: 'నేను ఒక అధికారిని',
    bn: 'আমি একজন কর্মকর্তা',
    ta: 'நான் ஒரு அதிகாரி',
    ml: 'ഞാൻ ഒരു ഉദ്യോഗസ്ഥനാണ്',
    kn: 'ನಾನು ಒಬ್ಬ ಅಧಿಕಾರಿ',
    gu: 'હું એક અધિકારી છું',
    mr: 'मी एक अधिकारी आहे',
    pa: 'ਮੈਂ ਇੱਕ ਅਧਿਕਾਰੀ ਹਾਂ',
    as: 'মই এজন বিষয়া',
    ur: 'میں ایک افسر ہوں',
    sd: 'مان هڪ آفيسر آهيان',
    ks: 'میں ایک آفیسر ہوں',
    ne: 'म एक अधिकारी हुं',
    bo: 'ང་བྷེ་པོ་ཞིག་ཡིན།',
    kok: 'हांव एक अधिकारी',
    mni: 'ঐ অমা অফিসার অমনি',
    sat: 'ᱤᱧ ᱫᱚ ᱢᱤᱫ ᱚᱯᱷᱤᱥᱚᱨ ᱠᱟᱱᱟᱧ',
    doi: 'मैं इक्क अधिकारी आं',
    mai: 'हम एक अधिकारी छी'
  },

  // Services
  'services.title': {
    hi: 'उपलब्ध सेवाएं',
    en: 'Available Services',
    od: 'ଉପଲବ୍ଧ ସେବା',
    te: 'అందుబాటులో ఉన్న సేవలు',
    bn: 'উপলব্ধ সেবাসমূহ',
    ta: 'கிடைக்கும் சேவைகள்',
    ml: 'ലഭ്യമായ സേവനങ്ങൾ',
    kn: 'ಲಭ್ಯವಿರುವ ಸೇವೆಗಳು',
    gu: 'ઉપલબ્ધ સેવાઓ',
    mr: 'उपलब्ध सेवा',
    pa: 'ਉਪਲਬਧ ਸੇਵਾਵਾਂ',
    as: 'উপলব্ধ সেৱাসমূহ',
    ur: 'دستیاب خدمات',
    sd: 'دستياب خدمتون',
    ks: 'دستیاب خدمات',
    ne: 'उपलब्ध सेवाहरू',
    bo: 'ཐོབ་རུང་བའི་ཞབས་ཏོག',
    kok: 'उपलब्ध सेवा',
    mni: 'ফাওবা সর্ভিসসিং',
    sat: 'ᱧᱟᱢᱚᱜ ᱠᱟᱱ ᱥᱮᱵᱟ ᱠᱚ',
    doi: 'उपलब्ध सेवायां',
    mai: 'उपलब्ध सेवासभ'
  },
  'services.description': {
    hi: 'जनजातीय समुदायों के लिए विशेष रूप से डिज़ाइन की गई सरकारी योजनाओं और सेवाओं का उपयोग करें',
    en: 'Access government schemes and services designed specifically for tribal communities',
    od: 'ଆଦିବାସୀ ସମ୍ପ୍ରଦାୟ ପାଇଁ ବିଶେଷ ଭାବରେ ଡିଜାଇନ୍ ହୋଇଥିବା ସରକାରୀ ଯୋଜନା ଏବଂ ସେବା ଗୁଡିକୁ ପ୍ରବେଶ କରନ୍ତୁ',
    te: 'గిరిజన సమాజాల కోసం ప్రత్యేకంగా రూపొందించిన ప్రభుత్వ పథకాలు మరియు సేవలను యాక్సెస్ చేయండి',
    bn: 'উপজাতীয় সম্প্রদায়ের জন্য বিশেষভাবে ডিজাইন করা সরকারি স্কিম এবং সেবা অ্যাক্সেস করুন',
    ta: 'பழங்குடியின சமூகங்களுக்கு குறிப்பாக வடிவமைக்கப்பட்ட அரசாங்க திட்டங்கள் மற்றும் சேவைகளை அணுகவும்',
    ml: 'ഗോത്രവർഗ സമൂഹങ്ങൾക്കായി പ്രത്യേകം രൂപകൽപ്പന ചെയ്ത സർക്കാർ പദ്ധതികളും സേവനങ്ങളും ആക്സസ് ചെയ്യുക',
    kn: 'ಬುಡಕಟ್ಟು ಸಮುದಾಯಗಳಿಗಾಗಿ ವಿಶೇಷವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ',
    gu: 'આદિવાસી સમુદાયો માટે ખાસ કરીને ડિઝાઇન કરાયેલી સરકારી યોજનાઓ અને સેવાઓનો ઉપયોગ કરો',
    mr: 'आदिवासी समुदायांसाठी विशेषतः डिझाइन केलेल्या सरकारी योजना आणि सेवांचा वापर करा',
    pa: 'ਆਦਿਵਾਸੀ ਸਮੁਦਾਇਆਂ ਲਈ ਖਾਸ ਤੌਰ ਤੇ ਤਿਆਰ ਕੀਤੀਆਂ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਸੇਵਾਵਾਂ ਦਾ ਉਪਯੋਗ ਕਰੋ',
    as: 'জনজাতীয় সম্প্ৰদায়ৰ বাবে বিশেষভাৱে ডিজাইন কৰা চৰকাৰী আঁচনি আৰু সেৱাসমূহ প্ৰৱেশ কৰক',
    ur: 'قبائلی کمیونٹیز کے لیے خاص طور پر ڈیزائن کی گئی سرکاری اسکیمز اور خدمات تک رسائی حاصل کریں',
    sd: 'قبائلي برادرين لاءِ خاص طور تي ڊزائين ٿيل سرڪاري اسڪيمن ۽ خدمتن تائين رسائي حاصل ڪريو',
    ks: 'قبائلی کمیونٹیز کے لیے خاص طور پر ڈیزائن کی گئی سرکاری اسکیمز اور خدمات تک رسائی حاصل کریں',
    ne: 'आदिवासी समुदायहरूको लागि विशेष गरी डिजाइन गरिएका सरकारी योजनाहरू र सेवाहरू पहुँच गर्नुहोस्',
    bo: 'མི་རིགས་ཚོགས་སྡེའི་དོན་དུ་བཟོས་པའི་གཞུང་གི་འཆར་གཞི་དང་ཞབས་ཏོག་ལ་ལྟ།',
    kok: 'आदिवासी समुदायां खातीर विशेष रुपान डिझाइन केलल्या सरकारी योजना अनी सेवांचो वापर करात',
    mni: 'ত্রিবাল কমিউনিটিসিংগীদমক স্পেসিয়েল ওইনা ডিজাইন তৌবা গবর্নমেন্ট স্কিমসিং অমসুং সর্ভিসসিং এক্সেস তৌ',
    sat: 'ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱦᱚᱲ ᱞᱟᱹᱜᱤᱫ ᱥᱟᱡᱟᱣ ᱟᱠᱟᱱ ᱥᱚᱨᱠᱟᱨᱤ ᱯᱞᱟᱱ ᱟᱨ ᱥᱮᱵᱟ ᱠᱚ ᱵᱮᱵᱷᱟᱨ ᱢᱮ',
    doi: 'आदिवासी समुदायां आस्तै विशेष रूप कन्ने डिजाइन कीतियां सरकारी योजनावां ते सेवावां दा इस्तेमाल करो',
    mai: 'आदिवासी समुदायसभक लेल विशेष रूपसँ डिजाइन कएल गेल सरकारी योजनासभ आ सेवासभक उपयोग करू'
  },
  'services.land_rights': {
    hi: 'भूमि अधिकार',
    en: 'Land Rights',
    od: 'ଜମି ଅଧିକାର',
    te: 'భూమి హక్కులు',
    bn: 'ভূমি অধিকার',
    ta: 'நில உரிமைகள்',
    ml: 'ഭൂമി അവകാശങ്ങൾ',
    kn: 'ಭೂಮಿ ಹಕ್ಕುಗಳು',
    gu: 'જમીન અધિકારો',
    mr: 'जमीन हक्क',
    pa: 'ਜ਼ਮੀਨ ਦੇ ਅਧਿਕਾਰ',
    as: 'ভূমি অধিকাৰ',
    ur: 'زمینی حقوق',
    sd: 'زمين جا حق',
    ks: 'زمین کے حقوق',
    ne: 'जग्गा अधिकार',
    bo: 'ས་ཆའི་ཐོབ་ཐང་།',
    kok: 'जमीन हक्क',
    mni: 'লৈ রাইত',
    sat: 'ᱚᱛ ᱟᱹᱫᱷᱟᱨ',
    doi: 'जमीन दे हक्क',
    mai: 'जमीनक अधिकार'
  },
  'services.land_rights_desc': {
    hi: 'भूमि पट्टा, स्वामित्व दस्तावेज और भूमि रिकॉर्ड सत्यापन के लिए आवेदन करें',
    en: 'Apply for land patta, ownership documents, and land record verification',
    od: 'ଜମି ପଟ୍ଟା, ମାଲିକାନା ଦଲିଲ, ଏବଂ ଜମି ରେକର୍ଡ ଯାଞ୍ଚ ପାଇଁ ଆବେଦନ କରନ୍ତୁ',
    te: 'భూమి పట్టా, యాజమాన్య పత్రాలు మరియు భూమి రికార్డు ధృవీకరణ కోసం దరఖాస్తు చేయండి',
    bn: 'ভূমি পাট্টা, মালিকানা নথি এবং ভূমি রেকর্ড যাচাইয়ের জন্য আবেদন করুন',
    ta: 'நில பட்டா, உரிமை ஆவணங்கள் மற்றும் நில பதிவு சரிபார்ப்பிற்கு விண்ணப்பிக்கவும்',
    ml: 'ഭൂമി പട്ടാ, ഉടമസ্થാവകാശ രേഖകൾ, ഭൂമി രേഖ സ്ഥിരീകരണം എന്നിവയ്ക്കായി അപേക്ഷിക്കുക',
    kn: 'ಭೂಮಿ ಪಟ್ಟಾ, ಮಾಲೀಕತ್ವ ದಾಖಲೆಗಳು ಮತ್ತು ಭೂಮಿ ದಾಖಲೆ ಪರಿಶೀಲನೆಗಾಗಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    gu: 'જમીન પટ્ટા, માલિકીના દસ્તાવેજો અને જમીન રેકોર્ડ ચકાસણી માટે અરજી કરો',
    mr: 'जमीन पट्टा, मालकी कागदपत्रे आणि जमीन रेकॉर्ड तपासणीसाठी अर्ज करा',
    pa: 'ਜ਼ਮੀਨ ਪੱਟਾ, ਮਾਲਕੀ ਦਸਤਾਵੇਜ਼ ਅਤੇ ਜ਼ਮੀਨ ਰਿਕਾਰਡ ਤਸਦੀਕ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    as: 'ভূমি পট্টা, মালিকানা দস্তাবেজ, আৰু ভূমি ৰেকৰ্ড সত্যাপনৰ বাবে আবেদন কৰক',
    ur: 'زمینی پٹا، ملکیتی دستاویزات اور زمینی ریکارڈ کی تصدیق کے لیے درخواست دیں',
    sd: 'زمين جي پٽي، ملڪيت جا دستاويز ۽ زمين جي رڪارڊ جي تصديق لاءِ درخواست ڏيو',
    ks: 'زمینی پٹا، ملکیتی دستاویزات اور زمینی ریکارڈ کی تصدیق کے لیے درخواست دیں',
    ne: 'जग्गा पत्ता, स्वामित्व कागजात र जग्गा रेकर्ड प्रमाणीकरणको लागि आवेदन दिनुहोस्',
    bo: 'ས་ཆའི་ཁྲིམས་ཡིག་དང་བདག་དབང་ཡིག་ཆ། ས་ཆའི་ཐོ་གཞུང་བདེན་དཔྱད་ཀྱི་ཞུ་བ་འབུལ།',
    kok: 'जमीन पट्टा, मालकी कागदपत्रां आणि जमीन रेकॉर्ड तपासणी खातीर अर्ज करात',
    mni: 'লৈ পট্টা, ওনারশিপ দকুমেন্তসিং অমসুং লৈ রেকর্ড ভেরিফিকেশনগীদমক এপ্লাই তৌ',
    sat: 'ᱚᱛ ᱯᱚᱴᱴᱟ, ᱢᱟᱞᱤᱠ ᱠᱟᱜᱚᱡ ᱟᱨ ᱚᱛ ᱨᱮᱠᱚᱨᱰ ᱧᱮᱞ ᱞᱟᱹᱜᱤᱫ ᱱᱮᱵᱮᱫᱚᱱ ᱢᱮ',
    doi: 'जमीन पत्ता, मालकी दस्तावेजां ते जमीन रेकॉर्ड सत्यापन आस्तै अर्जी दियो',
    mai: 'जमीन पट्टा, मालिकी दस्तावेज आ जमीन रेकर्ड सत्यापनक लेल आवेदन दिअ'
  },

  // Footer
  'footer.quick_links': {
    hi: 'त्वरित लिंक',
    en: 'Quick Links',
    od: 'ଶୀଘ୍ର ଲିଙ୍କ',
    te: 'త్వరిత లింకులు',
    bn: 'দ্রুত লিংক',
    ta: 'விரைவு இணைப்புகள்',
    ml: 'ക്വിക്ക് ലിങ്കുകൾ',
    kn: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    gu: 'ઝડપી લિંક્સ',
    mr: 'द्रुत दुवे',
    pa: 'ਤੇਜ਼ ਲਿੰਕ',
    as: 'দ্ৰুত লিংক',
    ur: 'فوری روابط',
    sd: 'تيز ڳنڍڻ',
    ks: 'فوری لنکس',
    ne: 'छिटो लिङ्कहरू',
    bo: 'མགྱོགས་པོའི་འབྲེལ་ལམ།',
    kok: 'जलदी लिंक',
    mni: 'অসোইবা লিংকসিং',
    sat: 'ᱞᱚᱜᱚᱱ ᱞᱤᱝᱠ ᱠᱚ',
    doi: 'जल्दी लिंक',
    mai: 'तुरंत लिंक'
  },
  'footer.support': {
    hi: 'सहायता',
    en: 'Support',
    od: 'ସହାୟତା',
    te: 'మద్దతు',
    bn: 'সহায়তা',
    ta: 'ஆதரவு',
    ml: 'പിന്തുണ',
    kn: 'ಬೆಂಬಲ',
    gu: 'સહાય',
    mr: 'समर्थन',
    pa: 'ਸਹਾਇਤਾ',
    as: 'সহায়',
    ur: 'مدد',
    sd: 'مدد',
    ks: 'مدد',
    ne: 'सहयोग',
    bo: 'རོགས་རམ།',
    kok: 'आदार',
    mni: 'সপোর্ত',
    sat: 'ᱜᱚᱲᱚ',
    doi: 'सहारा',
    mai: 'सहायता'
  },
  'footer.government': {
    hi: 'सरकार',
    en: 'Government',
    od: 'ସରକାର',
    te: 'ప్రభుత్వం',
    bn: 'সরকার',
    ta: 'அரசு',
    ml: 'സർക്കാർ',
    kn: 'ಸರ್ಕಾರ',
    gu: 'સરકાર',
    mr: 'सरकार',
    pa: 'ਸਰਕਾਰ',
    as: 'চৰকাৰ',
    ur: 'حکومت',
    sd: 'حڪومت',
    ks: 'حکومت',
    ne: 'सरकार',
    bo: 'གཞུང་།',
    kok: 'सरकार',
    mni: 'গবর্নমেন্ত',
    sat: 'ᱥᱚᱨᱠᱟᱨ',
    doi: 'सरकार',
    mai: 'सरकार'
  },
  'footer.copyright': {
    hi: '© 2024 भारत सरकार, जनजातीय मामलों का मंत्रालय। सभी अधिकार सुरक्षित।',
    en: '© 2024 Government of India, Ministry of Tribal Affairs. All rights reserved.',
    od: '© ୨୦୨୪ ଭାରତ ସରକାର, ଆଦିବାସୀ ବିଷୟ ମନ୍ତ୍ରଣାଳୟ। ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ।',
    te: '© 2024 భారత ప్రభుత్వం, గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ. అన్ని హక్కులు రక్షించబడ్డాయి.',
    bn: '© ২০২৪ ভারত সরকার, উপজাতীয় বিষয়ক মন্ত্রণালয়। সমস্ত অধিকার সংরক্ষিত।',
    ta: '© 2024 இந்திய அரசு, பழங்குடியினர் விவகார அமைச்சகம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன।',
    ml: '© 2024 ഇന്ത്യാ ഗവൺമെന്റ്, ഗോത്രവർഗ കാര്യ മന്ത്രാലയം. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതമാണ്.',
    kn: '© 2024 ಭಾರತ ಸರ್ಕಾರ, ಬುಡಕಟ್ಟು ವ್ಯವಹಾರಗಳ ಸಚಿವಾಲಯ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    gu: '© 2024 ભારત સરકાર, આદિવાસી બાબતોનું મંત્રાલય. બધા અધિકારો સુરક્ષિત છે.',
    mr: '© 2024 भारत सरकार, आदिवासी घडामोडी मंत्रालय. सर्व हक्क राखीव.',
    pa: '© 2024 ਭਾਰਤ ਸਰਕਾਰ, ਆਦਿਵਾਸੀ ਮਾਮਲਿਆਂ ਦਾ ਮੰਤਰਾਲਾ। ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',
    as: '© ২০২৪ ভাৰত চৰকাৰ, জনজাতীয় বিষয় মন্ত্ৰণালয়। সকলো অধিকাৰ সংৰক্ষিত।',
    ur: '© 2024 حکومت ہند، قبائلی امور کی وزارت۔ تمام حقوق محفوظ ہیں۔',
    sd: '© 2024 هندستان جي حڪومت، قبائلي معاملن جي وزارت. سمورا حق محفوظ آهن.',
    ks: '© 2024 حکومت ہند، قبائلی امور کی وزارت۔ تمام حقوق محفوظ ہیں۔',
    ne: '© 2024 भारत सरकार, आदिवासी मामिला मन्त्रालय। सबै अधिकार सुरक्षित।',
    bo: '© ༢༠༢༤ རྒྱ་གར་ཞིང་ཁབ། མི་རིགས་གནས་ཚུལ་ལས་ཁུངས། ཐོབ་ཐང་ཚང་མ་སྲུང་སྐྱོབ་ཡོད།',
    kok: '© 2024 भारत सरकार, आदिवासी मामले मंत्रालय। सगळे हक्क राखून दवरिल्लेत।',
    mni: '© ২০২৪ ভারত সরকার, ত্রিবাল অ্যাফেয়ার্স মিনিস্ট্রি। পুম্নমক রাইত ইক্কোয়না তৌরামীনি।',
    sat: '© ᱒᱐᱒᱔ ᱵᱷᱟᱨᱚᱛ ᱥᱚᱨᱠᱟᱨ, ᱟᱹᱫᱤᱵᱟᱹᱥᱤ ᱠᱟᱹᱢᱤ ᱢᱚᱱᱛᱨᱟᱞᱚᱭ᱾ ᱡᱷᱚᱛᱚ ᱟᱹᱫᱷᱟᱨ ᱫᱚᱦᱚᱭ ᱢᱮᱱᱟᱜᱼᱟ᱾',
    doi: '© 2024 भारत सरकार, आदिवासी मामले मंत्रालय। सारे हक्क सुरक्षित न।',
    mai: '© 2024 भारत सरकार, आदिवासी मामला मंत्रालय। सभ अधिकार सुरक्षित अछि।'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('hi');

  const t = (key: string): string => {
    return translations[key]?.[currentLanguage] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setCurrentLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
