import { createContext, useContext, useState, ReactNode } from "react";

const translations = {
  en: {
    title: "Tribal Affairs Portal",
    subtitle: "Government of India",
    citizen: "I am a Citizen",
    officer: "I am an Officer",
    newApplication: "New Application",
    applicationStatus: "Application Status",
    startApplication: "Start Application",
    checkStatus: "Check Status",
    backButton: "← Go Back",
    citizenServices: "Citizen Services",
    availableSchemes: "Available Schemes",
    applyNow: "Apply Now",
    personalInfo: "Personal Information",
    additionalInfo: "Additional Information",
    documents: "Documents",
    schemeSelection: "Scheme Selection",
    fullName: "Full Name",
    aadhaar: "Aadhaar Number",
    mobile: "Mobile Number",
    email: "Email Address",
    dob: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    fatherName: "Father's Name",
    caste: "Caste/Tribe",
    address: "Complete Address",
    village: "Village",
    district: "District",
    state: "State",
    pincode: "Pin Code",
    uploadDocuments: "Upload Required Documents",
    selectSchemes: "Select Schemes",
    submit: "Submit",
    next: "Next",
    previous: "Previous",
    back: "Back",
    applicationSubmitted: "Application Submitted Successfully",
    yourApplicationId: "Your Application ID",
    keepThisId: "Please keep this ID safe for future reference",
    returnToDashboard: "Return to Dashboard",
    downloadReceipt: "Download Receipt",
    // Officer Dashboard
    officerDashboard: "Officer Dashboard",
    welcomeBack: "Welcome back, manage tribal applications and land records",
    generateReport: "Generate Report",
    openMapView: "Open Map View",
    // Officer Login
    officerLogin: "Officer Login",
    enterOfficerCredentials: "Enter your credentials",
    officerId: "Officer ID",
    enterOfficerId: "Enter your Officer ID",
    password: "Password",
    enterPassword: "Enter your password",
    login: "Login",
    demoCredentials: "Demo Credentials",
    secureLogin: "Secure Government Login System",
    invalidCredentials: "Invalid Officer ID or Password",
    pendingApplications: "Pending Applications",
    approvedThisMonth: "Approved This Month",
    rejectedApplications: "Rejected Applications",
    landMarked: "Land Marked",
    applications: "Applications",
    analytics: "Analytics",
    landRecords: "Land Records",
    aiSupport: "AI Support",
    documentUpload: "Document Upload",
    uploadFRADocuments: "Upload FRA Documents",
    ocrExtraction: "OCR Text Extraction",
    aiDecisionSupport: "AI Decision Support System",
    exportReports: "Export Reports",
    extractText: "Extract Text",
    editText: "Edit Text",
    saveChanges: "Save Changes",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    processingDocument: "Processing document...",
    textExtracted: "Text extracted successfully",
    reviewAndEdit: "Review and edit extracted text",
    // Homepage
    govInitiative: "Government of India Initiative",
    tribalAffairs: "Tribal Affairs",
    digitalPortal: "Digital Portal",
    heroDescription: "Empowering tribal communities through digital governance. Apply for land rights, government benefits, and track your applications seamlessly.",
    availableServices: "Available Services",
    servicesDescription: "Access government schemes and services specially designed for tribal communities",
    landRights: "Land Rights",
    landRightsDesc: "Apply for land lease, ownership documents and land record verification",
    forestRightsAct: "Forest Rights Act",
    pmKisanDesc: "Direct benefit transfer for farmers with ₹6,000 annual support",
    perYear: "₹6,000/year",
    jalJeevanDesc: "Clean drinking water connection for every tribal household",
    waterConnection: "Water Connection",
    applicationsProcessed: "Applications Processed",
    landPattasApproved: "Land Pattas Approved",
    beneficiariesEnrolled: "Beneficiaries Enrolled",
    digitalAccuracy: "Digital Accuracy",
    quickLinks: "Quick Links",
    support: "Support",
    government: "Government",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    faqs: "FAQs",
    ministryTribal: "Ministry of Tribal Affairs",
    digitalIndia: "Digital India",
    myGov: "MyGov",
    // Citizen Portal
    newSchemeApplication: "Apply for a new scheme",
    checkYourApplication: "Check your application status",
    tribalScholarships: "Tribal Scholarships",
    scholarshipsDesc: "Educational scholarships for tribal students",
    tribalDevLoan: "Tribal Development Loan",
    tribalLoanDesc: "Low-interest loans for tribal entrepreneurs",
    underReview: "Under Review",
    approved: "Approved",
    pendingDocuments: "Pending Documents",
    rejected: "Rejected",
    // Officer Dashboard
    reviewAndProcess: "Review and process tribal applications",
    applicantName: "Applicant",
    scheme: "Scheme",
    location: "Location",
    landArea: "Land Area",
    submitted: "Submitted",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    review: "Review",
    approve: "Approve",
    reject: "Reject",
    analyticsReports: "Analytics & Reports",
    comprehensiveAnalysis: "Comprehensive analysis of tribal applications and demographics",
    statusDistribution: "Application Status Distribution",
    stateWiseApplications: "State-wise Applications",
    madhyaPradesh: "Madhya Pradesh",
    rajasthan: "Rajasthan",
    gujarat: "Gujarat",
    odisha: "Odisha",
    monthlyComparison: "Monthly Comparison"
  },
  hi: {
    title: "जनजातीय मामले पोर्टल",
    subtitle: "भारत सरकार",
    citizen: "मैं नागरिक हूं",
    officer: "मैं अधिकारी हूं",
    newApplication: "नया आवेदन",
    applicationStatus: "आवेदन की स्थिति",
    startApplication: "आवेदन शुरू करें",
    checkStatus: "स्थिति देखें",
    backButton: "← वापस जाएं",
    citizenServices: "नागरिक सेवाएं",
    availableSchemes: "उपलब्ध योजनाएं",
    applyNow: "आवेदन करें",
    personalInfo: "व्यक्तिगत जानकारी",
    additionalInfo: "पूरी जानकारी",
    documents: "दस्तावेज अपलोड",
    schemeSelection: "योजना चयन",
    fullName: "पूरा नाम",
    aadhaar: "आधार नंबर",
    mobile: "मोबाइल नंबर",
    email: "ईमेल पता",
    dob: "जन्म तारीख",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    fatherName: "पिता का नाम",
    caste: "जाति",
    address: "पूरा पता",
    village: "गांव",
    district: "जिला",
    state: "राज्य",
    pincode: "पिन कोड",
    uploadDocuments: "आवश्यक दस्तावेज अपलोड करें",
    selectSchemes: "योजनाओं का चयन करें",
    submit: "सबमिट करें",
    next: "अगला",
    previous: "पिछला",
    back: "वापस",
    applicationSubmitted: "आवेदन सफलतापूर्वक जमा हो गया",
    yourApplicationId: "आपका आवेदन नंबर",
    keepThisId: "कृपया इस नंबर को भविष्य के लिए संभाल कर रखें",
    returnToDashboard: "डैशबोर्ड पर वापस जाएं",
    downloadReceipt: "रसीद डाउनलोड करें",
    // Officer Dashboard
    officerDashboard: "अधिकारी डैशबोर्ड",
    welcomeBack: "वापस स्वागत है, जनजातीय आवेदन और भूमि रिकॉर्ड प्रबंधित करें",
    generateReport: "रिपोर्ट तैयार करें",
    openMapView: "मानचित्र दृश्य खोलें",
    // Officer Login
    officerLogin: "अधिकारी लॉगिन",
    enterOfficerCredentials: "अपनी जानकारी दर्ज करें",
    officerId: "अधिकारी आईडी",
    enterOfficerId: "अपनी अधिकारी आईडी दर्ज करें",
    password: "पासवर्ड",
    enterPassword: "अपना पासवर्ड दर्ज करें",
    login: "लॉगिन करें",
    demoCredentials: "डेमो क्रेडेंशियल",
    secureLogin: "सुरक्षित सरकारी लॉगिन सिस्टम",
    invalidCredentials: "गलत अधिकारी आईडी या पासवर्ड",
    pendingApplications: "लंबित आवेदन",
    approvedThisMonth: "इस महीने स्वीकृत",
    rejectedApplications: "अस्वीकृत आवेदन",
    landMarked: "भूमि चिह्नित",
    applications: "आवेदन",
    analytics: "विश्लेषण",
    landRecords: "भूमि रिकॉर्ड",
    aiSupport: "AI सहायता",
    documentUpload: "दस्तावेज़ अपलोड",
    uploadFRADocuments: "FRA दस्तावेज़ अपलोड करें",
    ocrExtraction: "OCR पाठ निष्कर्षण",
    aiDecisionSupport: "AI निर्णय सहायता प्रणाली",
    exportReports: "रिपोर्ट निर्यात",
    extractText: "पाठ निकालें",
    editText: "पाठ संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    exportPDF: "PDF निर्यात",
    exportExcel: "एक्सेल निर्यात",
    processingDocument: "दस्तावेज़ प्रसंस्करण...",
    textExtracted: "पाठ सफलतापूर्वक निकाला गया",
    reviewAndEdit: "निकाले गए पाठ की समीक्षा और संपादन करें",
    // Homepage
    govInitiative: "भारत सरकार की पहल",
    tribalAffairs: "जनजातीय मामले",
    digitalPortal: "डिजिटल पोर्टल",
    heroDescription: "डिजिटल गवर्नेंस के माध्यम से जनजातीय समुदायों को सशक्त बनाना। भूमि अधिकार, सरकारी लाभ के लिए आवेदन करें और अपने आवेदन को सहजता से ट्रैक करें।",
    availableServices: "उपलब्ध सेवाएं",
    servicesDescription: "जनजातीय समुदायों के लिए विशेष रूप से डिजाइन की गई सरकारी योजनाओं और सेवाओं का उपयोग करें",
    landRights: "भूमि अधिकार",
    landRightsDesc: "भूमि पट्टा, स्वामित्व दस्तावेज और भूमि रिकॉर्ड सत्यापन के लिए आवेदन करें",
    forestRightsAct: "Forest Rights Act",
    pmKisanDesc: "Direct benefit transfer for farmers with ₹6,000 annual support",
    perYear: "₹6,000/year",
    jalJeevanDesc: "Clean drinking water connection for every tribal household",
    waterConnection: "Water Connection",
    applicationsProcessed: "Applications Processed",
    landPattasApproved: "Land Pattas Approved",
    beneficiariesEnrolled: "Beneficiaries Enrolled",
    digitalAccuracy: "Digital Accuracy",
    quickLinks: "त्वरित लिंक",
    support: "सहायता",
    government: "सरकार",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    faqs: "FAQs",
    ministryTribal: "Ministry of Tribal Affairs",
    digitalIndia: "Digital India",
    myGov: "MyGov",
    // Citizen Portal
    newSchemeApplication: "नई योजना के लिए आवेदन करें",
    checkYourApplication: "अपने आवेदन की स्थिति जांचें",
    tribalScholarships: "Tribal Scholarships",
    scholarshipsDesc: "Educational scholarships for tribal students",
    tribalDevLoan: "Tribal Development Loan",
    tribalLoanDesc: "Low-interest loans for tribal entrepreneurs",
    underReview: "Under Review",
    approved: "Approved",
    pendingDocuments: "Pending Documents",
    rejected: "Rejected",
    // Officer Dashboard
    reviewAndProcess: "जनजातीय आवेदन की समीक्षा और प्रसंस्करण करें",
    applicantName: "आवेदक",
    scheme: "योजना",
    location: "स्थान",
    landArea: "भूमि क्षेत्र",
    submitted: "सबमिट किया",
    priority: "प्राथमिकता",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    review: "समीक्षा",
    approve: "स्वीकृत",
    reject: "अस्वीकार",
    analyticsReports: "विश्लेषण और रिपोर्ट",
    comprehensiveAnalysis: "जनजातीय आवेदनों और जनसांख्यिकी का व्यापक विश्लेषण",
    statusDistribution: "आवेदन स्थिति वितरण",
    stateWiseApplications: "राज्य-वार आवेदन",
    madhyaPradesh: "मध्य प्रदेश",
    rajasthan: "राजस्थान",
    gujarat: "गुजरात",
    odisha: "ओडिशा",
    monthlyComparison: "मासिक तुलना"
  },
  mr: {
    title: "आदिवासी व्यवहार पोर्टल",
    subtitle: "भारत सरकार",
    citizen: "मी नागरिक आहे",
    officer: "मी अधिकारी आहे",
    newApplication: "नवीन अर्ज",
    applicationStatus: "अर्जाची स्थिती",
    startApplication: "अर्ज सुरू करा",
    checkStatus: "स्थिती तपासा",
    backButton: "← परत जा",
    citizenServices: "नागरिक सेवा",
    availableSchemes: "उपलब्ध योजना",
    applyNow: "आता अर्ज करा",
    personalInfo: "वैयक्तिक माहिती",
    additionalInfo: "अतिरिक्त माहिती",
    documents: "कागदपत्रे",
    schemeSelection: "योजना निवड",
    fullName: "पूर्ण नाव",
    aadhaar: "आधार क्रमांक",
    mobile: "मोबाइल नंबर",
    email: "ईमेल पत्ता",
    dob: "जन्म तारीख",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "इतर",
    fatherName: "वडिलांचे नाव",
    caste: "जात",
    address: "पूर्ण पत्ता",
    village: "गाव",
    district: "जिल्हा",
    state: "राज्य",
    pincode: "पिन कोड",
    uploadDocuments: "आवश्यक कागदपत्रे अपलोड करा",
    selectSchemes: "योजना निवडा",
    submit: "सबमिट करा",
    next: "पुढे",
    previous: "मागे",
    back: "परत",
    applicationSubmitted: "अर्ज यशस्वीरित्या सबमिट झाला",
    yourApplicationId: "तुमचा अर्ज क्रमांक",
    keepThisId: "कृपया हा क्रमांक भविष्यासाठी सुरक्षित ठेवा",
    returnToDashboard: "डॅशबोर्डवर परत जा",
    downloadReceipt: "रसीद डाउनलोड करा",
    officerDashboard: "अधिकारी डॅशबोर्ड",
    welcomeBack: "परत स्वागत, आदिवासी अर्ज आणि जमीन रेकॉर्ड व्यवस्थापित करा",
    generateReport: "अहवाल तयार करा",
    openMapView: "नकाशा दृश्य उघडा",
    // Officer Login
    officerLogin: "अधिकारी लॉगिन",
    enterOfficerCredentials: "आपली माहिती प्रविष्ट करा",
    officerId: "अधिकारी आयडी",
    enterOfficerId: "आपली अधिकारी आयडी प्रविष्ट करा",
    password: "पासवर्ड",
    enterPassword: "आपला पासवर्ड प्रविष्ट करा",
    login: "लॉगिन करा",
    demoCredentials: "डेमो क्रेडेन्शियल",
    secureLogin: "सुरक्षित सरकारी लॉगिन प्रणाली",
    invalidCredentials: "चुकीची अधिकारी आयडी किंवा पासवर्ड",
    pendingApplications: "प्रलंबित अर्ज",
    approvedThisMonth: "या महिन्यात मंजूर",
    rejectedApplications: "नाकारलेले अर्ज",
    landMarked: "जमीन चिन्हांकित",
    applications: "अर्ज",
    analytics: "विश्लेषण",
    landRecords: "जमीन रेकॉर्ड",
    aiSupport: "AI सहाय्य",
    documentUpload: "दस्तऐवज अपलोड",
    uploadFRADocuments: "FRA दस्तऐवज अपलोड करा",
    ocrExtraction: "OCR मजकूर काढणे",
    aiDecisionSupport: "AI निर्णय सहाय्य प्रणाली",
    exportReports: "अहवाल निर्यात",
    extractText: "मजकूर काढा",
    editText: "मजकूर संपादित करा",
    saveChanges: "बदल सेव्ह करा",
    exportPDF: "PDF निर्यात",
    exportExcel: "एक्सेल निर्यात",
    processingDocument: "दस्तऐवज प्रक्रिया...",
    textExtracted: "मजकूर यशस्वीरित्या काढला",
    reviewAndEdit: "काढलेल्या मजकुराचे पुनरावलोकन आणि संपादन करा",
    // Homepage
    govInitiative: "भारत सरकारची उपक्रम",
    tribalAffairs: "आदिवासी व्यवहार",
    digitalPortal: "डिजिटल पोर्टल",
    heroDescription: "डिजिटल शासनाद्वारे आदिवासी समुदायांना सशक्त बनवणे. जमीन अधिकार, सरकारी लाभांसाठी अर्ज करा आणि तुमच्या अर्जांचा सहजपणे मागोवा घ्या.",
    availableServices: "उपलब्ध सेवा",
    servicesDescription: "आदिवासी समुदायांसाठी विशेषतः डिझाइन केलेल्या सरकारी योजना आणि सेवांचा वापर करा",
    landRights: "जमीन अधिकार",
    landRightsDesc: "जमीन भाडेपट्टी, मालकी दस्तऐवज आणि जमीन रेकॉर्ड पडताळणीसाठी अर्ज करा",
    forestRightsAct: "वन अधिकार कायदा",
    pmKisanDesc: "शेतकऱ्यांसाठी ₹6,000 वार्षिक सहाय्यासह थेट लाभ हस्तांतरण",
    perYear: "₹6,000/वर्ष",
    jalJeevanDesc: "प्रत्येक आदिवासी घराला स्वच्छ पिण्याच्या पाण्याचे कनेक्शन",
    waterConnection: "पाणी कनेक्शन",
    applicationsProcessed: "प्रक्रिया केलेले अर्ज",
    landPattasApproved: "मंजूर केलेले जमीन पट्टे",
    beneficiariesEnrolled: "नोंदणीकृत लाभार्थी",
    digitalAccuracy: "डिजिटल अचूकता",
    quickLinks: "द्रुत दुवे",
    support: "सहाय्य",
    government: "सरकार",
    helpCenter: "सहाय्य केंद्र",
    contactUs: "आमच्याशी संपर्क साधा",
    faqs: "वारंवार विचारले जाणारे प्रश्न",
    ministryTribal: "आदिवासी व्यवहार मंत्रालय",
    digitalIndia: "डिजिटल इंडिया",
    myGov: "माय गव्ह",
    // Citizen Portal
    newSchemeApplication: "नवीन योजनेसाठी अर्ज करा",
    checkYourApplication: "तुमच्या अर्जाची स्थिती तपासा",
    tribalScholarships: "आदिवासी शिष्यवृत्ती",
    scholarshipsDesc: "आदिवासी विद्यार्थ्यांसाठी शैक्षणिक शिष्यवृत्ती",
    tribalDevLoan: "आदिवासी विकास कर्ज",
    tribalLoanDesc: "आदिवासी उद्योजकांसाठी कमी व्याजदर कर्ज",
    underReview: "पुनरावलोकनाधीन",
    approved: "मंजूर",
    pendingDocuments: "प्रलंबित कागदपत्रे",
    rejected: "नाकारले",
    // Officer Dashboard
    reviewAndProcess: "आदिवासी अर्जांचे पुनरावलोकन आणि प्रक्रिया करा",
    applicantName: "अर्जदार",
    scheme: "योजना",
    location: "स्थान",
    landArea: "जमीन क्षेत्र",
    submitted: "सबमिट केले",
    priority: "प्राधान्यक्रम",
    high: "उच्च",
    medium: "मध्यम",
    low: "कमी",
    review: "पुनरावलोकन",
    approve: "मंजूर",
    reject: "नाकारा",
    analyticsReports: "विश्लेषण आणि अहवाल",
    comprehensiveAnalysis: "आदिवासी अर्ज आणि जनसांख्यिकीचे व्यापक विश्लेषण",
    statusDistribution: "अर्ज स्थिती वितरण",
    stateWiseApplications: "राज्यनिहाय अर्ज",
    madhyaPradesh: "मध्य प्रदेश",
    rajasthan: "राजस्थान",
    gujarat: "गुजरात",
    odisha: "ओडिशा",
    monthlyComparison: "मासिक तुलना",
    pmKisan: "PM किसान योजना",
    jalJivan: "जल जीवन मिशन"
  },
  gu: {
    title: "આદિવાસી બાબતોનું પોર્ટલ",
    subtitle: "ભારત સરકાર",
    citizen: "હું નાગરિક છું",
    officer: "હું અધિકારી છું",
    newApplication: "નવી અરજી",
    applicationStatus: "અરજીની સ્થિતિ",
    startApplication: "અરજી શરૂ કરો",
    checkStatus: "સ્થિતિ તપાસો",
    backButton: "← પાછા જાઓ",
    citizenServices: "નાગરિક સેવાઓ",
    availableSchemes: "ઉપલબ્ધ યોજનાઓ",
    applyNow: "હવે અરજી કરો",
    personalInfo: "વ્યક્તિગત માહિતી",
    additionalInfo: "વધારાની માહિતી",
    documents: "દસ્તાવેજો",
    schemeSelection: "યોજના પસંદગી",
    fullName: "પૂરું નામ",
    aadhaar: "આધાર નંબર",
    mobile: "મોબાઇલ નંબર",
    email: "ઇમેઇલ સરનામું",
    dob: "જન્મ તારીખ",
    gender: "લિંગ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    other: "અન્ય",
    fatherName: "પિતાનું નામ",
    caste: "જાતિ",
    address: "સંપૂર્ણ સરનામું",
    village: "ગામ",
    district: "જિલ્લો",
    state: "રાજ્ય",
    pincode: "પિન કોડ",
    uploadDocuments: "જરૂરી દસ્તાવેજો અપલોડ કરો",
    selectSchemes: "યોજનાઓ પસંદ કરો",
    submit: "સબમિટ કરો",
    next: "આગળ",
    previous: "પાછળ",
    back: "પાછા",
    applicationSubmitted: "અરજી સફળતાપૂર્વક સબમિટ થઈ",
    yourApplicationId: "તમારો અરજી નંબર",
    keepThisId: "કૃપા કરીને આ નંબર ભવિષ્ય માટે સુરક્ષિત રાખો",
    returnToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
    downloadReceipt: "રસીદ ડાઉનલોડ કરો",
    officerDashboard: "અધિકારી ડેશબોર્ડ",
    welcomeBack: "પાછા સ્વાગત, આદિવાસી અરજીઓ અને જમીન રેકોર્ડનું સંચાલન કરો",
    generateReport: "રિપોર્ટ જનરેટ કરો",
    openMapView: "મેપ વ્યૂ ખોલો",
    // Officer Login
    officerLogin: "અધિકારી લોગિન",
    enterOfficerCredentials: "તમારી માહિતી દાખલ કરો",
    officerId: "અધિકારી આઈડી",
    enterOfficerId: "તમારી અધિકારી આઈડી દાખલ કરો",
    password: "પાસવર્ડ",
    enterPassword: "તમારો પાસવર્ડ દાખલ કરો",
    login: "લોગિન કરો",
    demoCredentials: "ડેમો ક્રેડેન્શિયલ્સ",
    secureLogin: "સુરક્ષિત સરકારી લોગિન સિસ્ટમ",
    invalidCredentials: "ખોટી અધિકારી આઈડી અથવા પાસવર્ડ",
    pendingApplications: "પેન્ડિંગ અરજીઓ",
    approvedThisMonth: "આ મહિને મંજૂર",
    rejectedApplications: "નકારેલી અરજીઓ",
    landMarked: "જમીન ચિહ્નિત",
    applications: "અરજીઓ",
    analytics: "વિશ્લેષણ",
    landRecords: "જમીન રેકોર્ડ",
    aiSupport: "AI સહાય",
    documentUpload: "દસ્તાવેજ અપલોડ",
    uploadFRADocuments: "FRA દસ્તાવેજો અપલોડ કરો",
    ocrExtraction: "OCR ટેક્સ્ટ એક્સટ્રેક્શન",
    aiDecisionSupport: "AI ડિસિઝન સપોર્ટ સિસ્ટમ",
    exportReports: "રિપોર્ટ્સ એક્સપોર્ટ",
    extractText: "ટેક્સ્ટ એક્સટ્રેક્ટ કરો",
    editText: "ટેક્સ્ટ એડિટ કરો",
    saveChanges: "ચેન્જ સેવ કરો",
    exportPDF: "PDF એક્સપોર્ટ",
    exportExcel: "એક્સેલ એક્સપોર્ટ",
    processingDocument: "દસ્તાવેજ પ્રોસેસિંગ...",
    textExtracted: "ટેક્સ્ટ સફળતાપૂર્વક એક્સટ્રેક્ટ થયું",
    reviewAndEdit: "એક્સટ્રેક્ટ થયેલા ટેક્સ્ટની સમીક્ષા અને સંપાદન કરો",
    // Homepage
    govInitiative: "ભારત સરકારની પહેલ",
    tribalAffairs: "આદિવાસી બાબતો",
    digitalPortal: "ડિજિટલ પોર્ટલ",
    heroDescription: "ડિજિટલ શાસન દ્વારા આદિવાસી સમુદાયોને સશક્ત બનાવવું. જમીન અધિકારો, સરકારી લાભો માટે અરજી કરો અને તમારી અરજીઓને સરળતાથી ટ્રેક કરો.",
    availableServices: "ઉપલબ્ધ સેવાઓ",
    servicesDescription: "આદિવાસી સમુદાયો માટે ખાસ ડિઝાઇન કરેલી સરકારી યોજનાઓ અને સેવાઓનો ઉપયોગ કરો",
    landRights: "જમીન અધિકારો",
    landRightsDesc: "જમીન લીઝ, માલિકી દસ્તાવેજો અને જમીન રેકોર્ડ ચકાસણી માટે અરજી કરો",
    forestRightsAct: "વન અધિકાર અધિનિયમ",
    pmKisanDesc: "ખેડૂતો માટે ₹6,000 વાર્ષિક સહાય સાથે સીધો લાભ ટ્રાન્સફર",
    perYear: "₹6,000/વર્ષ",
    jalJeevanDesc: "દરેક આદિવાસી પરિવાર માટે સ્વચ્છ પીવાના પાણીનું કનેક્શન",
    waterConnection: "પાણી કનેક્શન",
    applicationsProcessed: "પ્રક્રિયા કરેલી અરજીઓ",
    landPattasApproved: "મંજૂર કરેલા જમીન પટ્ટા",
    beneficiariesEnrolled: "નોંધાયેલા લાભાર્થીઓ",
    digitalAccuracy: "ડિજિટલ ચોકસાઈ",
    quickLinks: "ઝડપી લિંક્સ",
    support: "સહાય",
    government: "સરકાર",
    helpCenter: "સહાય કેન્દ્ર",
    contactUs: "અમારો સંપર્ક કરો",
    faqs: "વારંવાર પૂછાતા પ્રશ્નો",
    ministryTribal: "આદિવાસી બાબતો મંત્રાલય",
    digitalIndia: "ડિજિટલ ઇન્ડિયા",
    myGov: "માય ગવ",
    // Citizen Portal
    newSchemeApplication: "નવી યોજના માટે અરજી કરો",
    checkYourApplication: "તમારી અરજીની સ્થિતિ તપાસો",
    tribalScholarships: "આદિવાસી શિષ્યવૃત્તિ",
    scholarshipsDesc: "આદિવાસી વિદ્યાર્થીઓ માટે શૈક્ષણિક શિષ્યવૃત્તિ",
    tribalDevLoan: "આદિવાસી વિકાસ લોન",
    tribalLoanDesc: "આદિવાસી ઉદ્યોગસાહસિકો માટે ઓછા વ્યાજ દરે લોન",
    underReview: "સમીક્ષા હેઠળ",
    approved: "મંજૂર",
    pendingDocuments: "પેન્ડિંગ દસ્તાવેજો",
    rejected: "નકારી કાઢ્યું",
    // Officer Dashboard
    reviewAndProcess: "આદિવાસી અરજીઓની સમીક્ષા અને પ્રક્રિયા કરો",
    applicantName: "અરજદાર",
    scheme: "યોજના",
    location: "સ્થાન",
    landArea: "જમીન વિસ્તાર",
    submitted: "સબમિટ કર્યું",
    priority: "પ્રાથમિકતા",
    high: "ઉચ્ચ",
    medium: "મધ્યમ",
    low: "નીચું",
    review: "સમીક્ષા",
    approve: "મંજૂર",
    reject: "નકારો",
    analyticsReports: "વિશ્લેષણ અને રિપોર્ટ્સ",
    comprehensiveAnalysis: "આદિવાસી અરજીઓ અને વસ્તી વિષયક માહિતીનું વ્યાપક વિશ્લેષણ",
    statusDistribution: "અરજી સ્થિતિ વિતરણ",
    stateWiseApplications: "રાજ્યવાર અરજીઓ",
    madhyaPradesh: "મધ્ય પ્રદેશ",
    rajasthan: "રાજસ્થાન",
    gujarat: "ગુજરાત",
    odisha: "ઓડિશા",
    monthlyComparison: "માસિક સરખામણી",
    pmKisan: "PM કિસાન યોજના",
    jalJivan: "જલ જીવન મિશન"
  },
  bn: {
    title: "উপজাতীয় বিষয়ক পোর্টাল",
    subtitle: "ভারত সরকার",
    citizen: "আমি একজন নাগরিক",
    officer: "আমি একজন কর্মকর্তা",
    newApplication: "নতুন আবেদন",
    applicationStatus: "আবেদনের অবস্থা",
    startApplication: "আবেদন শুরু করুন",
    checkStatus: "অবস্থা পরীক্ষা করুন",
    backButton: "← ফিরে যান",
    citizenServices: "নাগরিক সেবা",
    availableSchemes: "উপলব্ধ প্রকল্প",
    applyNow: "এখনই আবেদন করুন",
    personalInfo: "ব্যক্তিগত তথ্য",
    additionalInfo: "অতিরিক্ত তথ্য",
    documents: "নথিপত্র",
    schemeSelection: "প্রকল্প নির্বাচন",
    fullName: "সম্পূর্ণ নাম",
    aadhaar: "আধার নম্বর",
    mobile: "মোবাইল নম্বর",
    email: "ইমেইল ঠিকানা",
    dob: "জন্ম তারিখ",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    fatherName: "পিতার নাম",
    caste: "জাতি",
    address: "সম্পূর্ণ ঠিকানা",
    village: "গ্রাম",
    district: "জেলা",
    state: "রাজ্য",
    pincode: "পিন কোড",
    uploadDocuments: "প্রয়োজনীয় নথি আপলোড করুন",
    selectSchemes: "প্রকল্প নির্বাচন করুন",
    submit: "জমা দিন",
    next: "পরবর্তী",
    previous: "পূর্ববর্তী",
    back: "ফিরে",
    applicationSubmitted: "আবেদন সফলভাবে জমা দেওয়া হয়েছে",
    yourApplicationId: "আপনার আবেদন নম্বর",
    keepThisId: "ভবিষ্যতের জন্য এই নম্বরটি নিরাপদে রাখুন",
    returnToDashboard: "ড্যাশবোর্ডে ফিরে যান",
    downloadReceipt: "রসিদ ডাউনলোড করুন",
    officerDashboard: "কর্মকর্তা ড্যাশবোর্ড",
    welcomeBack: "স্বাগতম, উপজাতীয় আবেদন এবং ভূমি রেকর্ড পরিচালনা করুন",
    generateReport: "রিপোর্ট তৈরি করুন",
    openMapView: "মানচিত্র দেখুন",
    // Officer Login
    officerLogin: "কর্মকর্তা লগইন",
    enterOfficerCredentials: "আপনার তথ্য লিখুন",
    officerId: "কর্মকর্তা আইডি",
    enterOfficerId: "আপনার কর্মকর্তা আইডি লিখুন",
    password: "পাসওয়ার্ড",
    enterPassword: "আপনার পাসওয়ার্ড লিখুন",
    login: "লগইন করুন",
    demoCredentials: "ডেমো ক্রেডেনশিয়ালস",
    secureLogin: "নিরাপদ সরকারী লগইন সিস্টেম",
    invalidCredentials: "ভুল কর্মকর্তা আইডি বা পাসওয়ার্ড",
    pendingApplications: "অপেক্ষমাণ আবেদন",
    approvedThisMonth: "এই মাসে অনুমোদিত",
    rejectedApplications: "প্রত্যাখ্যাত আবেদন",
    landMarked: "ভূমি চিহ্নিত",
    applications: "আবেদন",
    analytics: "বিশ্লেষণ",
    landRecords: "ভূমি রেকর্ড",
    aiSupport: "AI সহায়তা",
    documentUpload: "নথি আপলোড",
    uploadFRADocuments: "FRA নথি আপলোড করুন",
    ocrExtraction: "OCR পাঠ্য নিষ্কাশন",
    aiDecisionSupport: "AI সিদ্ধান্ত সহায়তা ব্যবস্থা",
    exportReports: "রিপোর্ট রপ্তানি",
    extractText: "পাঠ্য নিষ্কাশন করুন",
    editText: "পাঠ্য সম্পাদনা করুন",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    exportPDF: "PDF রপ্তানি",
    exportExcel: "এক্সেল রপ্তানি",
    processingDocument: "নথি প্রক্রিয়াকরণ...",
    textExtracted: "পাঠ্য সফলভাবে নিষ্কাশিত",
    reviewAndEdit: "নিষ্কাশিত পাঠ্য পর্যালোচনা এবং সম্পাদনা করুন",
    // Homepage
    govInitiative: "ভারত সরকারের উদ্যোগ",
    tribalAffairs: "উপজাতীয় বিষয়",
    digitalPortal: "ডিজিটাল পোর্টাল",
    heroDescription: "ডিজিটাল শাসনের মাধ্যমে উপজাতীয় সম্প্রদায়কে ক্ষমতায়ন। জমির অধিকার, সরকারী সুবিধার জন্য আবেদন করুন এবং আপনার আবেদনগুলি সহজে ট্র্যাক করুন।",
    availableServices: "উপলব্ধ সেবা",
    servicesDescription: "উপজাতীয় সম্প্রদায়ের জন্য বিশেষভাবে ডিজাইন করা সরকারী প্রকল্প এবং সেবা ব্যবহার করুন",
    landRights: "জমির অধিকার",
    landRightsDesc: "জমি লিজ, মালিকানা নথি এবং জমি রেকর্ড যাচাইয়ের জন্য আবেদন করুন",
    forestRightsAct: "বন অধিকার আইন",
    pmKisanDesc: "কৃষকদের জন্য ₹6,000 বার্ষিক সহায়তা সহ সরাসরি সুবিধা স্থানান্তর",
    perYear: "₹6,000/বছর",
    jalJeevanDesc: "প্রতিটি উপজাতীয় পরিবারের জন্য পরিষ্কার পানীয় জল সংযোগ",
    waterConnection: "জল সংযোগ",
    applicationsProcessed: "প্রক্রিয়াকৃত আবেদন",
    landPattasApproved: "অনুমোদিত জমি পাট্টা",
    beneficiariesEnrolled: "নথিভুক্ত সুবিধাভোগী",
    digitalAccuracy: "ডিজিটাল নির্ভুলতা",
    quickLinks: "দ্রুত লিঙ্ক",
    support: "সহায়তা",
    government: "সরকার",
    helpCenter: "সহায়তা কেন্দ্র",
    contactUs: "আমাদের সাথে যোগাযোগ করুন",
    faqs: "প্রায়শ জিজ্ঞাসিত প্রশ্নাবলী",
    ministryTribal: "উপজাতীয় বিষয়ক মন্ত্রণালয়",
    digitalIndia: "ডিজিটাল ইন্ডিয়া",
    myGov: "মাই গভ",
    // Citizen Portal
    newSchemeApplication: "নতুন প্রকল্পের জন্য আবেদন করুন",
    checkYourApplication: "আপনার আবেদনের অবস্থা যাচাই করুন",
    tribalScholarships: "উপজাতীয় বৃত্তি",
    scholarshipsDesc: "উপজাতীয় শিক্ষার্থীদের জন্য শিক্ষাগত বৃত্তি",
    tribalDevLoan: "উপজাতীয় উন্নয়ন ঋণ",
    tribalLoanDesc: "উপজাতীয় উদ্যোক্তাদের জন্য কম সুদের ঋণ",
    underReview: "পর্যালোচনাধীন",
    approved: "অনুমোদিত",
    pendingDocuments: "অপেক্ষমাণ নথি",
    rejected: "প্রত্যাখ্যাত",
    // Officer Dashboard
    reviewAndProcess: "উপজাতীয় আবেদন পর্যালোচনা এবং প্রক্রিয়া করুন",
    applicantName: "আবেদনকারী",
    scheme: "প্রকল্প",
    location: "অবস্থান",
    landArea: "জমির এলাকা",
    submitted: "জমা দেওয়া হয়েছে",
    priority: "অগ্রাধিকার",
    high: "উচ্চ",
    medium: "মাঝারি",
    low: "নিম্ন",
    review: "পর্যালোচনা",
    approve: "অনুমোদন",
    reject: "প্রত্যাখ্যান",
    analyticsReports: "বিশ্লেষণ এবং প্রতিবেদন",
    comprehensiveAnalysis: "উপজাতীয় আবেদন এবং জনসংখ্যার বিস্তৃত বিশ্লেষণ",
    statusDistribution: "আবেদন অবস্থা বিতরণ",
    stateWiseApplications: "রাজ্যভিত্তিক আবেদন",
    madhyaPradesh: "মধ্যপ্রদেশ",
    rajasthan: "রাজস্থান",
    gujarat: "গুজরাট",
    odisha: "ওড়িশা",
    monthlyComparison: "মাসিক তুলনা",
    pmKisan: "PM কিষাণ যোজনা",
    jalJivan: "জল জীবন মিশন"
  },
  te: {
    title: "గిరిజన వ్యవహారాల పోర్టల్",
    subtitle: "భారత ప్రభుత్వం",
    citizen: "నేను పౌరుడను",
    officer: "నేను అధికారిని",
    newApplication: "కొత్త దరఖాస్తు",
    applicationStatus: "దరఖాస్తు స్థితి",
    startApplication: "దరఖాస్తు ప్రారంభించండి",
    checkStatus: "స్థితిని తనిఖీ చేయండి",
    backButton: "← వెనుకకు వెళ్ళండి",
    citizenServices: "పౌర సేవలు",
    availableSchemes: "అందుబాటులో ఉన్న పథకాలు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    personalInfo: "వ్యక్తిగత సమాచారం",
    additionalInfo: "అదనపు సమాచారం",
    documents: "పత్రాలు",
    schemeSelection: "పథకం ఎంపిక",
    fullName: "పూర్తి పేరు",
    aadhaar: "ఆధార్ నంబర్",
    mobile: "మొబైల్ నంబర్",
    email: "ఇమెయిల్ చిరునామా",
    dob: "పుట్టిన తేదీ",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతర",
    fatherName: "తండ్రి పేరు",
    caste: "కులం",
    address: "పూర్తి చిరునామా",
    village: "గ్రామం",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    pincode: "పిన్ కోడ్",
    uploadDocuments: "అవసరమైన పత్రాలను అప్‌లోడ్ చేయండి",
    selectSchemes: "పథకాలను ఎంచుకోండి",
    submit: "సమర్పించండి",
    next: "తరువాత",
    previous: "మునుపటి",
    back: "వెనుక",
    applicationSubmitted: "దరఖాస్తు విజయవంతంగా సమర్పించబడింది",
    yourApplicationId: "మీ దరఖాస్తు సంఖ్య",
    keepThisId: "భవిష్యత్ రిఫరెన్స్ కోసం ఈ సంఖ్యను భద్రంగా ఉంచండి",
    returnToDashboard: "డ్యాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
    downloadReceipt: "రసీదు డౌన్‌లోడ్ చేయండి",
    officerDashboard: "అధికారి డ్యాష్‌బోర్డ్",
    welcomeBack: "తిరిగి స్వాగతం, గిరిజన దరఖాస్తులు మరియు భూమి రికార్డులను నిర్వహించండి",
    generateReport: "నివేదిక రూపొందించండి",
    openMapView: "మ్యాప్ వ్యూ తెరవండి",
    // Officer Login
    officerLogin: "అధికారి లాగిన్",
    enterOfficerCredentials: "మీ వివరాలను నమోదు చేయండి",
    officerId: "అధికారి ఐడి",
    enterOfficerId: "మీ అధికారి ఐడిని నమోదు చేయండి",
    password: "పాస్‌వర్డ్",
    enterPassword: "మీ పాస్‌వర్డ్‌ను నమోదు చేయండి",
    login: "లాగిన్ చేయండి",
    demoCredentials: "డెమో ఆధారాలు",
    secureLogin: "సురక్షిత ప్రభుత్వ లాగిన్ వ్యవస్థ",
    invalidCredentials: "తప్పుడు అధికారి ఐడి లేదా పాస్‌వర్డ్",
    pendingApplications: "పెండింగ్ దరఖాస్తులు",
    approvedThisMonth: "ఈ నెలలో ఆమోదించబడింది",
    rejectedApplications: "తిరస్కరించబడిన దరఖాస్తులు",
    landMarked: "భూమి గుర్తించబడింది",
    applications: "దరఖాస్తులు",
    analytics: "విశ్లేషణలు",
    landRecords: "భూమి రికార్డులు",
    aiSupport: "AI మద్దతు",
    documentUpload: "పత్రం అప్‌లోడ్",
    uploadFRADocuments: "FRA పత్రాలను అప్‌లోడ్ చేయండి",
    ocrExtraction: "OCR టెక్స్ట్ ఎక్స్‌ట్రాక్షన్",
    aiDecisionSupport: "AI నిర్ణయ మద్దతు వ్యవస్థ",
    exportReports: "నివేదికలను ఎగుమతి చేయండి",
    extractText: "టెక్స్ట్ ఎక్స్‌ట్రాక్ట్ చేయండి",
    editText: "టెక్స్ట్ సవరించండి",
    saveChanges: "మార్పులను సేవ్ చేయండి",
    exportPDF: "PDF ఎగుమతి",
    exportExcel: "ఎక్సెల్ ఎగుమతి",
    processingDocument: "పత్రం ప్రాసెసింగ్...",
    textExtracted: "టెక్స్ట్ విజయవంతంగా ఎక్స్‌ట్రాక్ట్ చేయబడింది",
    reviewAndEdit: "ఎక్స్‌ట్రాక్ట్ చేసిన టెక్స్ట్‌ను సమీక్షించండి మరియు సవరించండి",
    // Homepage
    govInitiative: "భారత ప్రభుత్వ చొరవ",
    tribalAffairs: "గిరిజన వ్యవహారాలు",
    digitalPortal: "డిజిటల్ పోర్టల్",
    heroDescription: "డిజిటల్ పాలన ద్వారా గిరిజన సమాజాలకు శక్తినివ్వడం. భూమి హక్కులు, ప్రభుత్వ ప్రయోజనాల కోసం దరఖాస్తు చేయండి మరియు మీ దరఖాస్తులను సజావుగా ట్రాక్ చేయండి.",
    availableServices: "అందుబాటులో ఉన్న సేవలు",
    servicesDescription: "గిరిజన సమాజాల కోసం ప్రత్యేకంగా రూపొందించిన ప్రభుత్వ పథకాలు మరియు సేవలను ఉపయోగించండి",
    landRights: "భూమి హక్కులు",
    landRightsDesc: "భూమి లీజు, యాజమాన్య పత్రాలు మరియు భూమి రికార్డు ధృవీకరణ కోసం దరఖాస్తు చేయండి",
    forestRightsAct: "అటవీ హక్కుల చట్టం",
    pmKisanDesc: "రైతులకు ₹6,000 వార్షిక మద్దతుతో ప్రత్యక్ష ప్రయోజన బదిలీ",
    perYear: "₹6,000/సంవత్సరం",
    jalJeevanDesc: "ప్రతి గిరిజన కుటుంబానికి శుభ్రమైన త్రాగునీటి కనెక్షన్",
    waterConnection: "నీటి కనెక్షన్",
    applicationsProcessed: "ప్రాసెస్ చేయబడిన దరఖాస్తులు",
    landPattasApproved: "ఆమోదించబడిన భూమి పట్టాలు",
    beneficiariesEnrolled: "నమోదు చేయబడిన లబ్ధిదారులు",
    digitalAccuracy: "డిజిటల్ ఖచ్చితత్వం",
    quickLinks: "శీఘ్ర లింకులు",
    support: "మద్దతు",
    government: "ప్రభుత్వం",
    helpCenter: "సహాయ కేంద్రం",
    contactUs: "మమ్మల్ని సంప్రదించండి",
    faqs: "తరచుగా అడిగే ప్రశ్నలు",
    ministryTribal: "గిరిజన వ్యవహారాల మంత్రిత్వ శాఖ",
    digitalIndia: "డిజిటల్ ఇండియా",
    myGov: "మై గవ్",
    // Citizen Portal
    newSchemeApplication: "కొత్త పథకం కోసం దరఖాస్తు చేయండి",
    checkYourApplication: "మీ దరఖాస్తు స్థితిని తనిఖీ చేయండి",
    tribalScholarships: "గిరిజన స్కాలర్‌షిప్‌లు",
    scholarshipsDesc: "గిరిజన విద్యార్థులకు విద్యా స్కాలర్‌షిప్‌లు",
    tribalDevLoan: "గిరిజన అభివృద్ధి రుణం",
    tribalLoanDesc: "గిరిజన వ్యవసాయదారులకు తక్కువ వడ్డీ రుణాలు",
    underReview: "సమీక్షలో ఉంది",
    approved: "ఆమోదించబడింది",
    pendingDocuments: "పెండింగ్ పత్రాలు",
    rejected: "తిరస్కరించబడింది",
    // Officer Dashboard
    reviewAndProcess: "గిరిజన దరఖాస్తులను సమీక్షించండి మరియు ప్రాసెస్ చేయండి",
    applicantName: "దరఖాస్తుదారు",
    scheme: "పథకం",
    location: "స్థానం",
    landArea: "భూమి విస్తీర్ణం",
    submitted: "సమర్పించబడింది",
    priority: "ప్రాధాన్యత",
    high: "అధిక",
    medium: "మధ్యస్థం",
    low: "తక్కువ",
    review: "సమీక్ష",
    approve: "ఆమోదించు",
    reject: "తిరస్కరించు",
    analyticsReports: "విశ్లేషణలు మరియు నివేదికలు",
    comprehensiveAnalysis: "గిరిజన దరఖాస్తులు మరియు జనాభా యొక్క సమగ్ర విశ్లేషణ",
    statusDistribution: "దరఖాస్తు స్థితి పంపిణీ",
    stateWiseApplications: "రాష్ట్రవారీ దరఖాస్తులు",
    madhyaPradesh: "మధ్యప్రదేశ్",
    rajasthan: "రాజస్థాన్",
    gujarat: "గుజరాత్",
    odisha: "ఒడిశా",
    monthlyComparison: "నెలవారీ పోలిక",
    pmKisan: "PM కిసాన్ యోజన",
    jalJivan: "జల జీవన్ మిషన్"
  },
  or: {
    title: "ଆଦିବାସୀ ବ୍ୟାପାର ପୋର୍ଟାଲ",
    subtitle: "ଭାରତ ସରକାର",
    citizen: "ମୁଁ ଜଣେ ନାଗରିକ",
    officer: "ମୁଁ ଜଣେ ଅଧିକାରୀ",
    newApplication: "ନୂତନ ଆବେଦନ",
    applicationStatus: "ଆବେଦନର ସ୍ଥିତି",
    startApplication: "ଆବେଦନ ଆରମ୍ଭ କରନ୍ତୁ",
    checkStatus: "ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ",
    backButton: "← ପଛକୁ ଯାଆନ୍ତୁ",
    citizenServices: "ନାଗରିକ ସେବା",
    availableSchemes: "ଉପଲବ୍ଧ ଯୋଜନା",
    applyNow: "ବର୍ତ୍ତମାନ ଆବେଦନ କରନ୍ତୁ",
    personalInfo: "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
    additionalInfo: "ଅତିରିକ୍ତ ସୂଚନା",
    documents: "ଦଲିଲପତ୍ର",
    schemeSelection: "ଯୋଜନା ଚୟନ",
    fullName: "ସମ୍ପୂର୍ଣ୍ଣ ନାମ",
    aadhaar: "ଆଧାର ନମ୍ବର",
    mobile: "ମୋବାଇଲ ନମ୍ବର",
    email: "ଇମେଇଲ ଠିକଣା",
    dob: "ଜନ୍ମ ତାରିଖ",
    gender: "ଲିଙ୍ଗ",
    male: "ପୁରୁଷ",
    female: "ମହିଳା",
    other: "ଅନ୍ୟାନ୍ୟ",
    fatherName: "ପିତାଙ୍କ ନାମ",
    caste: "ଜାତି",
    address: "ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା",
    village: "ଗାଁ",
    district: "ଜିଲ୍ଲା",
    state: "ରାଜ୍ୟ",
    pincode: "ପିନ କୋଡ",
    uploadDocuments: "ଆବଶ୍ୟକ ଦଲିଲପତ୍ର ଅପଲୋଡ କରନ୍ତୁ",
    selectSchemes: "ଯୋଜନା ଚୟନ କରନ୍ତୁ",
    submit: "ଦାଖଲ କରନ୍ତୁ",
    next: "ପରବର୍ତ୍ତୀ",
    previous: "ପୂର୍ବବର୍ତ୍ତୀ",
    back: "ପଛ",
    applicationSubmitted: "ଆବେଦନ ସଫଳତାର ସହିତ ଦାଖଲ ହୋଇଛି",
    yourApplicationId: "ଆପଣଙ୍କର ଆବେଦନ ନମ୍ବର",
    keepThisId: "ଭବିଷ୍ୟତ ରେଫରେନ୍ସ ପାଇଁ ଏହି ନମ୍ବରକୁ ସୁରକ୍ଷିତ ରଖନ୍ତୁ",
    returnToDashboard: "ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ",
    downloadReceipt: "ରସିଦ ଡାଉନଲୋଡ କରନ୍ତୁ",
    officerDashboard: "ଅଧିକାରୀ ଡ୍ୟାସବୋର୍ଡ",
    welcomeBack: "ସ୍ୱାଗତ, ଆଦିବାସୀ ଆବେଦନ ଏବଂ ଜମି ରେକର୍ଡ ପରିଚାଳନା କରନ୍ତୁ",
    generateReport: "ରିପୋର୍ଟ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
    openMapView: "ମାନଚିତ୍ର ଦେଖନ୍ତୁ",
    // Officer Login
    officerLogin: "ଅଧିକାରୀ ଲଗଇନ୍",
    enterOfficerCredentials: "ଆପଣଙ୍କର ତଥ୍ୟ ପ୍ରବିଷ୍ଟ କରନ୍ତୁ",
    officerId: "ଅଧିକାରୀ ଆଇଡି",
    enterOfficerId: "ଆପଣଙ୍କର ଅଧିକାରୀ ଆଇଡି ପ୍ରବିଷ୍ଟ କରନ୍ତୁ",
    password: "ପାସୱାର୍ଡ",
    enterPassword: "ଆପଣଙ୍କର ପାସୱାର୍ଡ ପ୍ରବିଷ୍ଟ କରନ୍ତୁ",
    login: "ଲଗଇନ୍ କରନ୍ତୁ",
    demoCredentials: "ଡେମୋ ପ୍ରମାଣପତ୍ର",
    secureLogin: "ସୁରକ୍ଷିତ ସରକାରୀ ଲଗଇନ୍ ବ୍ୟବସ୍ଥା",
    invalidCredentials: "ଭୁଲ ଅଧିକାରୀ ଆଇଡି କିମ୍ବା ପାସୱାର୍ଡ",
    pendingApplications: "ପେଣ୍ଡିଂ ଆବେଦନ",
    approvedThisMonth: "ଏହି ମାସରେ ଅନୁମୋଦିତ",
    rejectedApplications: "ପ୍ରତ୍ୟାଖ୍ୟାନ ହୋଇଥିବା ଆବେଦନ",
    landMarked: "ଜମି ଚିହ୍ନିତ",
    applications: "ଆବେଦନଗୁଡ଼ିକ",
    analytics: "ବିଶ୍ଳେଷଣ",
    landRecords: "ଜମି ରେକର୍ଡ",
    aiSupport: "AI ସହାୟତା",
    documentUpload: "ଦଲିଲ ଅପଲୋଡ",
    uploadFRADocuments: "FRA ଦଲିଲ ଅପଲୋଡ କରନ୍ତୁ",
    ocrExtraction: "OCR ଟେକ୍ସଟ ନିଷ୍କାସନ",
    aiDecisionSupport: "AI ନିଷ୍ପତ୍ତି ସହାୟତା ବ୍ୟବସ୍ଥା",
    exportReports: "ରିପୋର୍ଟ ରପ୍ତାନି",
    extractText: "ଟେକ୍ସଟ ନିଷ୍କାସନ କରନ୍ତୁ",
    editText: "ଟେକ୍ସଟ ଏଡିଟ କରନ୍ତୁ",
    saveChanges: "ପରିବର୍ତ୍ତନ ସେଭ କରନ୍ତୁ",
    exportPDF: "PDF ରପ୍ତାନି",
    exportExcel: "ଏକ୍ସେଲ ରପ୍ତାନି",
    processingDocument: "ଦଲିଲ ପ୍ରକ୍ରିୟାକରଣ...",
    textExtracted: "ଟେକ୍ସଟ ସଫଳତାର ସହିତ ନିଷ୍କାସିତ",
    reviewAndEdit: "ନିଷ୍କାସିତ ଟେକ୍ସଟର ସମୀକ୍ଷା ଏବଂ ସମ୍ପାଦନା କରନ୍ତୁ",
    // Homepage
    govInitiative: "ଭାରତ ସରକାରଙ୍କ ପଦକ୍ଷେପ",
    tribalAffairs: "ଆଦିବାସୀ ବ୍ୟାପାର",
    digitalPortal: "ଡିଜିଟାଲ ପୋର୍ଟାଲ",
    heroDescription: "ଡିଜିଟାଲ ଶାସନ ମାଧ୍ୟମରେ ଆଦିବାସୀ ସମ୍ପ୍ରଦାୟକୁ ସଶକ୍ତିକରଣ। ଜମି ଅଧିକାର, ସରକାରୀ ଲାଭ ପାଇଁ ଆବେଦନ କରନ୍ତୁ ଏବଂ ଆପଣଙ୍କର ଆବେଦନଗୁଡ଼ିକୁ ସହଜରେ ଟ୍ରାକ କରନ୍ତୁ।",
    availableServices: "ଉପଲବ୍ଧ ସେବା",
    servicesDescription: "ଆଦିବାସୀ ସମ୍ପ୍ରଦାୟ ପାଇଁ ବିଶେଷ ଭାବରେ ଡିଜାଇନ କରାଯାଇଥିବା ସରକାରୀ ଯୋଜନା ଏବଂ ସେବା ବ୍ୟବହାର କରନ୍ତୁ",
    landRights: "ଜମି ଅଧିକାର",
    landRightsDesc: "ଜମି ଲିଜ, ମାଲିକାନା ଦଲିଲ ଏବଂ ଜମି ରେକର୍ଡ ଯାଞ୍ଚ ପାଇଁ ଆବେଦନ କରନ୍ତୁ",
    forestRightsAct: "ବନ ଅଧିକାର ଅଧିନିୟମ",
    pmKisanDesc: "କୃଷକମାନଙ୍କ ପାଇଁ ₹6,000 ବାର୍ଷିକ ସହାୟତା ସହିତ ପ୍ରତ୍ୟକ୍ଷ ଲାଭ ସ୍ଥାନାନ୍ତର",
    perYear: "₹6,000/ବର୍ଷ",
    jalJeevanDesc: "ପ୍ରତ୍ୟେକ ଆଦିବାସୀ ପରିବାର ପାଇଁ ସ୍ୱଚ୍ଛ ପାନୀୟ ଜଳ ସଂଯୋଗ",
    waterConnection: "ଜଳ ସଂଯୋଗ",
    applicationsProcessed: "ପ୍ରକ୍ରିୟାକୃତ ଆବେଦନ",
    landPattasApproved: "ଅନୁମୋଦିତ ଜମି ପଟ୍ଟା",
    beneficiariesEnrolled: "ନାମାଙ୍କିତ ଲାଭାନ୍ବିତ",
    digitalAccuracy: "ଡିଜିଟାଲ ସଠିକତା",
    quickLinks: "ଦ୍ରୁତ ଲିଙ୍କ",
    support: "ସହାୟତା",
    government: "ସରକାର",
    helpCenter: "ସହାୟତା କେନ୍ଦ୍ର",
    contactUs: "ଆମକୁ ସମ୍ପର୍କ କରନ୍ତୁ",
    faqs: "ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ",
    ministryTribal: "ଆଦିବାସୀ ବ୍ୟାପାର ମନ୍ତ୍ରଣାଳୟ",
    digitalIndia: "ଡିଜିଟାଲ ଇଣ୍ଡିଆ",
    myGov: "ମାଇ ଗଭ",
    // Citizen Portal
    newSchemeApplication: "ନୂତନ ଯୋଜନା ପାଇଁ ଆବେଦନ କରନ୍ତୁ",
    checkYourApplication: "ଆପଣଙ୍କର ଆବେଦନର ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ",
    tribalScholarships: "ଆଦିବାସୀ ବୃତ୍ତି",
    scholarshipsDesc: "ଆଦିବାସୀ ଛାତ୍ରମାନଙ୍କ ପାଇଁ ଶିକ୍ଷାଗତ ବୃତ୍ତି",
    tribalDevLoan: "ଆଦିବାସୀ ବିକାଶ ଋଣ",
    tribalLoanDesc: "ଆଦିବାସୀ ଉଦ୍ୟୋଗୀଙ୍କ ପାଇଁ କମ ସୁଧ ଋଣ",
    underReview: "ସମୀକ୍ଷାଧୀନ",
    approved: "ଅନୁମୋଦିତ",
    pendingDocuments: "ପେଣ୍ଡିଂ ଦଲିଲ",
    rejected: "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    // Officer Dashboard
    reviewAndProcess: "ଆଦିବାସୀ ଆବେଦନଗୁଡ଼ିକର ସମୀକ୍ଷା ଏବଂ ପ୍ରକ୍ରିୟା କରନ୍ତୁ",
    applicantName: "ଆବେଦନକାରୀ",
    scheme: "ଯୋଜନା",
    location: "ସ୍ଥାନ",
    landArea: "ଜମି କ୍ଷେତ୍ର",
    submitted: "ଦାଖଲ କରାଯାଇଛି",
    priority: "ପ୍ରାଥମିକତା",
    high: "ଉଚ୍ଚ",
    medium: "ମଧ୍ୟମ",
    low: "କମ୍",
    review: "ସମୀକ୍ଷା",
    approve: "ଅନୁମୋଦନ",
    reject: "ପ୍ରତ୍ୟାଖ୍ୟାନ",
    analyticsReports: "ବିଶ୍ଳେଷଣ ଏବଂ ରିପୋର୍ଟ",
    comprehensiveAnalysis: "ଆଦିବାସୀ ଆବେଦନ ଏବଂ ଜନସଂଖ୍ୟାର ବ୍ୟାପକ ବିଶ୍ଳେଷଣ",
    statusDistribution: "ଆବେଦନ ସ୍ଥିତି ବଣ୍ଟନ",
    stateWiseApplications: "ରାଜ୍ୟଭିତ୍ତିକ ଆବେଦନ",
    madhyaPradesh: "ମଧ୍ୟ ପ୍ରଦେଶ",
    rajasthan: "ରାଜସ୍ଥାନ",
    gujarat: "ଗୁଜରାଟ",
    odisha: "ଓଡ଼ିଶା",
    monthlyComparison: "ମାସିକ ତୁଳନା",
    pmKisan: "PM କିଷାଣ ଯୋଜନା",
    jalJivan: "ଜଳ ଜୀବନ ମିଶନ"
  }
};

type Language = 'en' | 'hi' | 'mr' | 'gu' | 'bn' | 'te' | 'or';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('hi');

  const t = (key: TranslationKey): string => {
    // Ensure we have a valid language, fallback to 'hi' if not
    const validLanguage = translations[language] ? language : 'hi';
    return translations[validLanguage][key] || translations['hi'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Provide fallback values if context is not available
    return {
      language: 'hi' as Language,
      setLanguage: () => {},
      t: (key: TranslationKey) => translations.hi[key] || key
    };
  }
  return context;
};


